#!/usr/bin/env python3
"""
Add batch of AWS implementation guide data for high-priority controls.
Based on MCP queries already performed.
"""

import json
from pathlib import Path
from datetime import datetime, timezone

def main():
    """Add AWS controls for AU-3, SI-3, AC-6, CM-3, AU-6, and SC-13."""
    
    # Load existing data
    data_file = Path(__file__).parent / 'compliance_discovery' / 'aws_controls_mcp_data.json'
    
    with open(data_file, 'r') as f:
        data = json.load(f)
    
    print(f"Loaded existing data with {data['metadata']['total_controls_mapped']} controls")
    
    # AU-3: Audit Record Content (CloudTrail)
    data['controls']['au-3'] = [
        {
            "control_id": "AWS-CG-0000008",
            "title": "Configure AWS CloudTrail trails to be multi-region",
            "description": "Configure CloudTrail to support multi-Region trails to centralize log aggregation of all events for audit log reviews.",
            "services": ["AWS CloudTrail"],
            "config_rules": ["MULTI_REGION_CLOUD_TRAIL_ENABLED"],
            "security_hub_controls": ["CloudTrail.1"],
            "control_tower_ids": ["SH.CloudTrail.1"],
            "frameworks": ["NIST-SP-800-53-r5", "ISO-IEC-27001:2013-Annex-A", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000014",
            "title": "Enable log file validation for AWS CloudTrail logs",
            "description": "Protect log files generated by CloudTrail against tampering or unauthorized modifications to support log file integrity and reliability.",
            "services": ["AWS CloudTrail"],
            "config_rules": ["CLOUD_TRAIL_LOG_FILE_VALIDATION_ENABLED"],
            "security_hub_controls": ["CloudTrail.4"],
            "control_tower_ids": ["CT.CLOUDTRAIL.PR.2", "SH.CloudTrail.4"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0"]
        },
        {
            "control_id": "AWS-CG-0000686",
            "title": "Enable Amazon S3 data event logging for read operations in AWS CloudTrail",
            "description": "Configure AWS CloudTrail to log all Amazon S3 read data events using multi-Region trails for comprehensive auditing of S3 object-level read activities.",
            "services": ["AWS CloudTrail"],
            "config_rules": ["CLOUDTRAIL_ALL_READ_S3_DATA_EVENT_CHECK"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.CLOUDTRAIL.DT.3"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # SI-3: Malicious Code Protection (GuardDuty)
    data['controls']['si-3'] = [
        {
            "control_id": "AWS-CG-0000645",
            "title": "Enable Malware Protection in Amazon GuardDuty",
            "description": "Activate Malware Protection feature in Amazon GuardDuty to detect potential malware in your AWS environment.",
            "services": ["Amazon GuardDuty"],
            "config_rules": ["GUARDDUTY_MALWARE_PROTECTION_ENABLED"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.GUARDDUTY.DT.2"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000180",
            "title": "Enable Amazon GuardDuty in AWS account and region",
            "description": "Implement intrusion detection (IDS) capabilities by enabling GuardDuty to monitor for and detect suspicious activity.",
            "services": ["Amazon GuardDuty"],
            "config_rules": ["GUARDDUTY_ENABLED_CENTRALIZED"],
            "security_hub_controls": ["GuardDuty.1"],
            "control_tower_ids": ["SH.GuardDuty.1"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000616",
            "title": "Enable Amazon EKS Audit Log Monitoring in GuardDuty",
            "description": "Activate Amazon EKS Audit Log Monitoring feature in Amazon GuardDuty for enhanced security monitoring of Kubernetes clusters.",
            "services": ["Amazon GuardDuty"],
            "config_rules": ["GUARDDUTY_EKS_PROTECTION_AUDIT_ENABLED"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.GUARDDUTY.DT.3"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # AC-6: Least Privilege (IAM)
    data['controls']['ac-6'] = [
        {
            "control_id": "AWS-CG-0000479",
            "title": "Prevent IAM inline policies from using wildcard permissions in both Action and Resource elements",
            "description": "Restrict IAM inline policies from including 'Effect' 'Allow' with 'Action' '*' over 'Resource' '*' to enforce least privilege access.",
            "services": ["AWS Identity and Access Management"],
            "config_rules": [],
            "security_hub_controls": [],
            "control_tower_ids": ["CT.IAM.PR.1"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000761",
            "title": "Restrict IAM inline policies from using wildcard service actions",
            "description": "Restrict IAM inline policies from using 'Effect' 'Allow' with wildcard service actions to enforce least privilege access.",
            "services": ["AWS Identity and Access Management"],
            "config_rules": [],
            "security_hub_controls": [],
            "control_tower_ids": ["CT.IAM.PR.5"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000185",
            "title": "Manage access in AWS by creating policies and attaching them to IAM identities",
            "description": "Manage access in AWS by creating and attaching IAM policies to ensure that only authorized individuals have access to data and resources.",
            "services": ["AWS Identity and Access Management"],
            "config_rules": ["IAM_POLICY_IN_USE"],
            "security_hub_controls": ["IAM.18"],
            "control_tower_ids": [],
            "frameworks": ["NIST-SP-800-53-r5", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # CM-3: Configuration Change Control (CloudFormation, Config)
    data['controls']['cm-3'] = [
        {
            "control_id": "AWS-CG-0000466",
            "title": "Prevent unauthorized changes to AWS Config settings",
            "description": "Blocks all users and roles, except the AWS Control Tower service role, from modifying or disabling AWS Config settings.",
            "services": ["AWS Config"],
            "config_rules": [],
            "security_hub_controls": [],
            "control_tower_ids": ["AWS-GR_CONFIG_CHANGE_PROHIBITED"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000080",
            "title": "Send event notifications from AWS CloudFormation stacks to an Amazon SNS topic",
            "description": "Send event notifications from CloudFormation stacks to an SNS topic to notify personnel of potential security events.",
            "services": ["AWS CloudFormation"],
            "config_rules": ["CLOUDFORMATION_STACK_NOTIFICATION_CHECK"],
            "security_hub_controls": ["CloudFormation.1"],
            "control_tower_ids": ["CONFIG.CLOUDFORMATION.DT.1"],
            "frameworks": ["NIST-SP-800-53-r5"]
        },
        {
            "control_id": "AWS-CG-0000465",
            "title": "Prevent unauthorized modifications to AWS Config Rules managed by Control Tower",
            "description": "Blocks all users and roles, except the AWS Control Tower service role, from modifying or deleting AWS Config rules.",
            "services": ["AWS Config"],
            "config_rules": [],
            "security_hub_controls": [],
            "control_tower_ids": ["AWS-GR_CONFIG_RULE_CHANGE_PROHIBITED"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # AU-6: Audit Review, Analysis, and Reporting (CloudWatch, Security Hub)
    data['controls']['au-6'] = [
        {
            "control_id": "AWS-CG-0000017",
            "title": "Ensure Amazon CloudWatch alarms cannot be disabled",
            "description": "Ensure Amazon CloudWatch alarms cannot be disabled to allow continuous monitoring and timely responses to critical workloads.",
            "services": ["Amazon CloudWatch"],
            "config_rules": ["CLOUDWATCH_ALARM_ACTION_ENABLED_CHECK"],
            "security_hub_controls": ["CloudWatch.17"],
            "control_tower_ids": ["CONFIG.CLOUDWATCH.DT.1"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0"]
        },
        {
            "control_id": "AWS-CG-0000244",
            "title": "Define retention periods for Amazon CloudWatch Log groups",
            "description": "Define retention periods for CloudWatch Log groups to ensure that stored logs are retained for as long as the business requires.",
            "services": ["Amazon CloudWatch Logs"],
            "config_rules": ["CW_LOGGROUP_RETENTION_PERIOD_CHECK"],
            "security_hub_controls": ["CloudWatch.16"],
            "control_tower_ids": ["CONFIG.LOGS.DT.2"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v3.2.1"]
        },
        {
            "control_id": "AWS-CG-0000169",
            "title": "Enable AWS Security Hub service",
            "description": "Activate Security Hub in the AWS management console and configure the service to receive findings from supported AWS security services.",
            "services": ["AWS Security Hub"],
            "config_rules": ["SECURITYHUB_ENABLED"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.SECURITYHUB.DT.1"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # SC-13: Cryptographic Protection (FIPS, encryption standards)
    data['controls']['sc-13'] = [
        {
            "control_id": "AWS-CG-0000358",
            "title": "Enable encryption for data in transit for Amazon DynamoDB Accelerator (DAX) endpoint",
            "description": "Enable encryption for data in transit for Amazon DynamoDB Accelerator (DAX) endpoint to prevent unintended information disclosure.",
            "services": ["Amazon DynamoDB Accelerator (DAX)"],
            "config_rules": ["DAX_TLS_ENDPOINT_ENCRYPTION"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.DAX.DT.1"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000613",
            "title": "Enable encryption in transit for AWS AppSync API caches",
            "description": "Configure encryption in transit for AWS AppSync API caches to secure data transmission between services.",
            "services": ["AWS AppSync"],
            "config_rules": ["APPSYNC_CACHE_CT_ENCRYPTION_IN_TRANSIT"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.APPSYNC.DT.3"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        },
        {
            "control_id": "AWS-CG-0000894",
            "title": "EMR Security Configuration Encryption at Rest Enabled",
            "description": "Monitors Amazon EMR security configurations to verify that encryption at rest is properly enabled.",
            "services": ["Amazon Elastic MapReduce"],
            "config_rules": ["EMR_SECURITY_CONFIGURATION_ENCRYPTION_REST"],
            "security_hub_controls": [],
            "control_tower_ids": ["CONFIG.EMR.DT.3"],
            "frameworks": ["NIST-SP-800-53-r5", "PCI-DSS-v4.0", "SSAE-18-SOC-2-Oct-2023"]
        }
    ]
    
    # Update metadata
    data['metadata']['total_controls_mapped'] = len(data['controls'])
    data['metadata']['export_date'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    
    # Save updated data
    with open(data_file, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"Added 6 new controls:")
    print(f"  ✓ AU-3: Audit Record Content (3 AWS controls)")
    print(f"  ✓ SI-3: Malicious Code Protection (3 AWS controls)")
    print(f"  ✓ AC-6: Least Privilege (3 AWS controls)")
    print(f"  ✓ CM-3: Configuration Change Control (3 AWS controls)")
    print(f"  ✓ AU-6: Audit Review (3 AWS controls)")
    print(f"  ✓ SC-13: Cryptographic Protection (3 AWS controls)")
    print(f"\nTotal controls in file: {data['metadata']['total_controls_mapped']}")
    print(f"Data saved to: {data_file}")


if __name__ == '__main__':
    main()
