"""Custom discovery questions for CMMC Level 2 practices.

These questions are designed to guide SAS advisors through specific, actionable
conversations with customer teams pursuing CMMC Level 2 certification. Each
question references concrete AWS services, processes, and tools relevant to
protecting Controlled Unclassified Information (CUI) in DoD contractor
environments.

Only IMPLEMENTATION questions are custom here. Evidence, second-line, and
audit-readiness questions are always generated by the standard generator.
"""

from typing import List, Dict, Optional

# =========================================================================
# CMMC Level 2 practice-specific implementation questions
# Each practice maps to a list of dicts with 'question' key
# =========================================================================
CMMC_CUSTOM_QUESTIONS: Dict[str, List[Dict[str, str]]] = {

    # =========================================================================
    # AC — Access Control
    # =========================================================================

    "AC.L2-3.1.1": [
        {
            "question": "Walk us through how you control who and what can access systems that store or process CUI. For example, do you use AWS IAM Identity Center (SSO) with your corporate identity provider to manage user access, or are you using local IAM users?"
        },
        {
            "question": "How do you handle service accounts and automated processes that need access to CUI? Are you using IAM roles with scoped permissions rather than long-lived access keys?"
        },
    ],
    "AC.L2-3.1.2": [
        {
            "question": "How do you restrict what authorized users can actually do once they're logged in? For example, do you use IAM policies that limit actions to specific resources, or do users have broad admin-level access?"
        },
        {
            "question": "Can you show us how different roles (e.g., developer, analyst, admin) have different permission sets? Are you using IAM permission boundaries or AWS Organizations SCPs to enforce these limits?"
        },
    ],
    "AC.L2-3.1.3": [
        {
            "question": "How do you control where CUI can flow within your environment? For example, do you use VPC security groups, network ACLs, or AWS Network Firewall rules to prevent CUI from moving to unauthorized network segments?"
        },
        {
            "question": "Do you have data flow diagrams that show how CUI moves between systems, users, and external partners? How do you enforce those approved paths — for instance, using S3 bucket policies, VPC endpoints, or PrivateLink?"
        },
    ],
    "AC.L2-3.1.4": [
        {
            "question": "How do you separate duties so that no single person can perform all critical steps of a sensitive process? For example, can the same person who deploys code to production also approve the deployment?"
        },
        {
            "question": "In your AWS environment, do you use separate IAM roles for different functions — like one role for infrastructure provisioning and another for security configuration? Are there SCPs or permission boundaries preventing role overlap?"
        },
    ],
    "AC.L2-3.1.5": [
        {
            "question": "How do you enforce least privilege for user accounts and service roles? For example, do your IAM policies grant only the specific actions needed, or do you see broad wildcard permissions like s3:* or ec2:*?"
        },
        {
            "question": "How do you handle privileged accounts (root, admin)? Are they protected with MFA, used only for break-glass scenarios, and monitored with CloudTrail alerts for any usage?"
        },
    ],
    "AC.L2-3.1.6": [
        {
            "question": "When administrators perform non-security tasks like browsing documentation or checking email, do they use a separate non-privileged account? Or do they use their admin credentials for everything?"
        },
        {
            "question": "In AWS, do your admins have separate IAM roles — one for day-to-day work and another elevated role they assume only when performing privileged operations? How is this enforced?"
        },
    ],
    "AC.L2-3.1.7": [
        {
            "question": "How do you prevent regular users from running privileged commands or accessing admin functions? For example, are IAM policies configured to deny actions like iam:CreateUser or ec2:RunInstances for non-admin roles?"
        },
        {
            "question": "When someone attempts a privileged action they shouldn't, is that captured in audit logs? Are you using CloudTrail to log denied API calls and alerting on suspicious privilege escalation attempts?"
        },
    ],
    "AC.L2-3.1.8": [
        {
            "question": "What happens after multiple failed login attempts? Do you lock accounts or introduce delays? For example, does your identity provider (Okta, Azure AD) enforce lockout policies after 3-5 failed attempts?"
        },
        {
            "question": "For AWS console access via IAM Identity Center or federation, how are failed login attempts tracked and limited? Do you have CloudWatch alarms or GuardDuty findings that alert on brute-force attempts?"
        },
    ],
    "AC.L2-3.1.9": [
        {
            "question": "When users log into systems that handle CUI, do they see a notice explaining authorized use, monitoring, and consent? For example, is there a login banner on your AWS WorkSpaces, EC2 bastion hosts, or VPN portal?"
        },
    ],
    "AC.L2-3.1.10": [
        {
            "question": "Do workstations and remote sessions automatically lock after a period of inactivity? What's the timeout — 5 minutes, 15 minutes? Does the lock screen hide all CUI content?"
        },
        {
            "question": "For AWS WorkSpaces or remote desktop sessions used to access CUI, are session timeout and screen lock policies enforced through Group Policy, WorkSpaces settings, or endpoint management tools?"
        },
    ],
    "AC.L2-3.1.11": [
        {
            "question": "Do user sessions automatically terminate after a defined period of inactivity or other conditions (e.g., end of business day, token expiration)? What are your timeout values for web apps, SSH sessions, and console access?"
        },
    ],
    "AC.L2-3.1.12": [
        {
            "question": "How do you monitor remote access sessions — VPN connections, SSH sessions, RDP, or AWS Systems Manager Session Manager? Can you see who connected, when, from where, and what they did?"
        },
        {
            "question": "Are you using AWS Systems Manager Session Manager instead of opening SSH/RDP ports? Session Manager provides built-in logging, access control through IAM, and eliminates the need for bastion hosts."
        },
    ],
    "AC.L2-3.1.13": [
        {
            "question": "Are all remote access sessions encrypted? For example, do VPN connections use IPsec or TLS, SSH uses strong ciphers, and RDP connections use TLS? How do you verify encryption is actually in use?"
        },
        {
            "question": "For AWS access, are you using HTTPS for console and API calls, and encrypted tunnels (Site-to-Site VPN or Direct Connect with MACsec) for network connectivity to your VPCs?"
        },
    ],
    "AC.L2-3.1.14": [
        {
            "question": "Does all remote access flow through a managed access control point — like a VPN concentrator, jump box, or AWS Client VPN endpoint — rather than allowing direct connections to individual systems?"
        },
    ],
    "AC.L2-3.1.15": [
        {
            "question": "Who is authorized to run privileged commands remotely, and how is that authorization documented? For example, can a remote admin restart services, modify security groups, or change IAM policies — and is there an approval process?"
        },
    ],
    "AC.L2-3.1.16": [
        {
            "question": "Do you have a process for authorizing wireless access points and wireless-enabled devices before they connect to networks that handle CUI? How do you detect and respond to rogue wireless access points?"
        },
    ],
    "AC.L2-3.1.17": [
        {
            "question": "Are your wireless networks protected with WPA3 or WPA2-Enterprise with 802.1X authentication? How do you separate wireless networks that may access CUI from guest or general-purpose wireless?"
        },
    ],
    "AC.L2-3.1.18": [
        {
            "question": "How do you control which mobile devices (phones, tablets, laptops) can connect to systems containing CUI? Do you use a Mobile Device Management (MDM) solution that enforces encryption, screen lock, and remote wipe?"
        },
    ],
    "AC.L2-3.1.19": [
        {
            "question": "Is CUI encrypted on all mobile devices and laptops? For example, are laptops using BitLocker or FileVault with full-disk encryption, and are mobile devices using hardware-backed encryption? What happens if a device is lost or stolen?"
        },
    ],
    "AC.L2-3.1.20": [
        {
            "question": "How do you verify and control connections to external systems — like partner networks, cloud services, or SaaS applications — that may process CUI? Do you have agreements in place that define security requirements for these connections?"
        },
        {
            "question": "In AWS, do you use VPC peering, Transit Gateway, or PrivateLink to control connections to external systems? Are there security group rules and NACLs that restrict traffic to only approved external endpoints?"
        },
    ],
    "AC.L2-3.1.21": [
        {
            "question": "Do you restrict the use of USB drives, external hard drives, and other portable storage on systems that access CUI? For example, are USB ports disabled via Group Policy, endpoint protection, or device control software?"
        },
    ],
    "AC.L2-3.1.22": [
        {
            "question": "How do you ensure CUI is not posted on publicly accessible websites, file shares, or cloud storage? Do you have controls to prevent accidental public exposure — like S3 Block Public Access, content review processes, or DLP tools?"
        },
        {
            "question": "Are you using Amazon Macie to scan S3 buckets for sensitive data that might be publicly accessible? Do you have AWS Config rules like S3_BUCKET_PUBLIC_READ_PROHIBITED and S3_BUCKET_PUBLIC_WRITE_PROHIBITED enabled?"
        },
    ],

    # =========================================================================
    # AT — Awareness and Training
    # =========================================================================

    "AT.L2-3.2.1": [
        {
            "question": "What security awareness training do you provide to all users who access systems with CUI? Does it cover topics like phishing, social engineering, CUI handling rules, and reporting suspicious activity? How often is it delivered?"
        },
        {
            "question": "Is the training tailored to different roles — for example, do system administrators get deeper technical training than general users? Do you track completion rates and follow up with people who haven't completed it?"
        },
    ],
    "AT.L2-3.2.2": [
        {
            "question": "How do you ensure that people in security-related roles (system admins, security analysts, incident responders) have the specific technical training they need? For example, do AWS administrators receive training on IAM best practices, CloudTrail analysis, or GuardDuty triage?"
        },
    ],
    "AT.L2-3.2.3": [
        {
            "question": "Do you provide training on recognizing insider threat indicators — like unusual data downloads, after-hours access to CUI, or attempts to bypass security controls? How do employees report concerns, and is there a non-retaliation policy?"
        },
    ],

    # =========================================================================
    # AU — Audit and Accountability
    # =========================================================================

    "AU.L2-3.3.1": [
        {
            "question": "What events do you log across your systems — user logins, file access, configuration changes, failed authentication attempts? In AWS, is CloudTrail enabled in all regions with both management and data events captured?"
        },
        {
            "question": "How long do you retain audit logs? CMMC assessors will want to see logs going back far enough to support incident investigation. Are logs stored in S3 with lifecycle policies, or in CloudWatch Logs with defined retention periods?"
        },
    ],
    "AU.L2-3.3.2": [
        {
            "question": "Can you trace any action in your systems back to a specific individual? For example, if a file containing CUI was downloaded, can you identify exactly who did it and when? Are shared or generic accounts prohibited?"
        },
        {
            "question": "In AWS, are you using individual IAM users or federated identities (not shared credentials) so that every API call in CloudTrail is attributable to a specific person?"
        },
    ],
    "AU.L2-3.3.3": [
        {
            "question": "How often do you review which events are being logged and update your logging configuration? For example, when you deploy a new AWS service or application, do you verify that appropriate audit events are being captured?"
        },
    ],
    "AU.L2-3.3.4": [
        {
            "question": "What happens if audit logging fails or stops — for example, if CloudTrail is disabled, a log pipeline breaks, or disk space runs out on a syslog server? Do you have alerts that notify your team immediately?"
        },
        {
            "question": "In AWS, do you have CloudWatch alarms or EventBridge rules that detect when CloudTrail logging is stopped or modified? Is there an SCP preventing anyone from disabling CloudTrail?"
        },
    ],
    "AU.L2-3.3.5": [
        {
            "question": "Do you correlate logs from different sources to detect suspicious patterns? For example, combining CloudTrail API logs with VPC Flow Logs and GuardDuty findings to investigate a potential breach? What tools do you use — SIEM, CloudWatch Logs Insights, Amazon Detective?"
        },
    ],
    "AU.L2-3.3.6": [
        {
            "question": "Can you generate on-demand reports from your audit logs — for example, 'show me all access to CUI repositories in the last 30 days' or 'list all IAM policy changes this quarter'? What tools support this — Athena queries on CloudTrail logs, SIEM dashboards, or Security Hub reports?"
        },
    ],
    "AU.L2-3.3.7": [
        {
            "question": "Are all your systems synchronized to a common time source so that timestamps in audit logs are consistent and can be correlated? In AWS, EC2 instances use the Amazon Time Sync Service by default — but what about on-premises systems and applications?"
        },
    ],
    "AU.L2-3.3.8": [
        {
            "question": "How do you protect audit logs from being tampered with or deleted? For example, are CloudTrail logs stored in an S3 bucket with Object Lock enabled, in a separate logging account that application teams cannot access?"
        },
        {
            "question": "Who has access to modify or delete audit logs? Is access to the logging infrastructure restricted to a small security team with separate credentials from the systems being monitored?"
        },
    ],
    "AU.L2-3.3.9": [
        {
            "question": "Is the ability to configure audit logging restricted to authorized administrators only? For example, can a regular developer disable CloudTrail or modify log retention settings, or is that locked down via IAM policies and SCPs?"
        },
    ],

    # =========================================================================
    # CM — Configuration Management
    # =========================================================================

    "CM.L2-3.4.1": [
        {
            "question": "Do you maintain documented baseline configurations for your systems — servers, network devices, workstations, cloud resources? In AWS, are you using AWS Config to track resource configurations and detect drift from your baselines?"
        },
        {
            "question": "Do you maintain a current inventory of all hardware and software in your CUI environment? How do you track what's deployed — AWS Config resource inventory, Systems Manager Inventory, or a CMDB?"
        },
    ],
    "CM.L2-3.4.2": [
        {
            "question": "How do you establish and enforce security configuration settings — for example, CIS Benchmarks for operating systems, AWS Foundational Security Best Practices, or custom hardening guides? Are these enforced automatically or checked manually?"
        },
        {
            "question": "In AWS, are you using Security Hub with the CIS AWS Foundations Benchmark or AWS Foundational Security Best Practices standard enabled? Do you have AWS Config rules that automatically flag non-compliant configurations?"
        },
    ],
    "CM.L2-3.4.3": [
        {
            "question": "How do you manage changes to your systems — is there a formal change management process with request, review, approval, and documentation steps? Who approves changes to systems that handle CUI?"
        },
        {
            "question": "In AWS, do you use CloudFormation or CDK for infrastructure changes (so changes are version-controlled and reviewable), or are changes made manually through the console? Are CloudTrail logs reviewed to detect unauthorized changes?"
        },
    ],
    "CM.L2-3.4.4": [
        {
            "question": "Before making a change to a system that handles CUI, do you analyze the potential security impact? For example, if someone wants to open a new port in a security group or add a new IAM policy, is there a security review step?"
        },
    ],
    "CM.L2-3.4.5": [
        {
            "question": "Who can make changes to systems in your CUI environment, and how is that access controlled? Are change permissions restricted to specific IAM roles, and are physical access controls in place for on-premises equipment?"
        },
    ],
    "CM.L2-3.4.6": [
        {
            "question": "How do you ensure systems only provide the capabilities that are actually needed? For example, do you disable unnecessary services, remove unused software, and restrict AWS services to only those required for the workload using SCPs?"
        },
    ],
    "CM.L2-3.4.7": [
        {
            "question": "How do you identify and disable nonessential programs, ports, protocols, and services? For example, are security groups configured to allow only required ports, and are unused AWS services blocked by SCPs or IAM policies?"
        },
    ],
    "CM.L2-3.4.8": [
        {
            "question": "Do you use application whitelisting (allow only approved software to run) or blacklisting (block known-bad software)? For example, are you using AWS Systems Manager application control, AppLocker on Windows, or similar tools on your CUI systems?"
        },
    ],
    "CM.L2-3.4.9": [
        {
            "question": "How do you control software that users install on their own — browser extensions, utilities, personal applications? Is user-installed software monitored and restricted on systems that access CUI?"
        },
    ],

    # =========================================================================
    # IA — Identification and Authentication
    # =========================================================================

    "IA.L2-3.5.1": [
        {
            "question": "How do you uniquely identify every user, process, and device that accesses your CUI systems? For example, does every person have their own account (no shared accounts), and are service accounts individually named and tracked?"
        },
    ],
    "IA.L2-3.5.2": [
        {
            "question": "How do you verify that users are who they claim to be before granting access? What authentication methods are in use — passwords, certificates, tokens, biometrics? For AWS, are you using IAM Identity Center with your corporate identity provider?"
        },
    ],
    "IA.L2-3.5.3": [
        {
            "question": "Is multifactor authentication (MFA) required for all privileged accounts and for network access to non-privileged accounts? For example, is MFA enforced on the AWS root account, all IAM users with console access, and VPN connections?"
        },
        {
            "question": "What types of MFA are you using — hardware tokens, authenticator apps, or SMS? For AWS, are you using virtual MFA devices, hardware TOTP tokens, or FIDO2 security keys? Is MFA enforced via IAM policies or Identity Center settings?"
        },
    ],
    "IA.L2-3.5.4": [
        {
            "question": "Are your authentication mechanisms resistant to replay attacks? For example, do you use time-based one-time passwords (TOTP), challenge-response protocols, or token-based authentication that prevents captured credentials from being reused?"
        },
    ],
    "IA.L2-3.5.5": [
        {
            "question": "When a user leaves or an account is decommissioned, how long before that username or identifier can be reassigned to someone else? Do you have a policy preventing reuse of identifiers for a defined period to avoid confusion in audit logs?"
        },
    ],
    "IA.L2-3.5.6": [
        {
            "question": "How do you handle accounts that haven't been used in a while? For example, do you automatically disable IAM users after 90 days of inactivity? Are you using IAM credential reports or Access Analyzer to identify stale accounts?"
        },
    ],
    "IA.L2-3.5.7": [
        {
            "question": "What are your password requirements — minimum length, complexity (uppercase, lowercase, numbers, special characters), and how many characters must change when creating a new password? Do these meet or exceed DoD standards (typically 15+ characters)?"
        },
    ],
    "IA.L2-3.5.8": [
        {
            "question": "How many previous passwords do you track to prevent reuse? For example, does your identity provider enforce that users cannot reuse any of their last 24 passwords?"
        },
    ],
    "IA.L2-3.5.9": [
        {
            "question": "When you issue a temporary password (for new accounts or password resets), is the user forced to change it immediately upon first login? How do you securely deliver temporary passwords to users?"
        },
    ],
    "IA.L2-3.5.10": [
        {
            "question": "Are passwords stored using strong one-way hashing (like bcrypt or PBKDF2) rather than in plaintext or reversible encryption? When passwords are transmitted, is it always over encrypted channels (HTTPS, TLS)?"
        },
        {
            "question": "In AWS, are you using Secrets Manager or Parameter Store (SecureString) for any application credentials rather than hardcoding them? Are IAM access keys rotated regularly?"
        },
    ],
    "IA.L2-3.5.11": [
        {
            "question": "When users type their password, is the input masked (shown as dots or asterisks) so that someone looking over their shoulder can't see it? Does this apply to all login screens — web apps, terminal sessions, and remote desktop?"
        },
    ],

    # =========================================================================
    # IR — Incident Response
    # =========================================================================

    "IR.L2-3.6.1": [
        {
            "question": "Do you have a documented incident response plan that covers preparation, detection, analysis, containment, eradication, and recovery? Does it specifically address incidents involving CUI — like unauthorized access to CUI, CUI data exfiltration, or ransomware affecting CUI systems?"
        },
        {
            "question": "Does your plan include AWS-specific runbooks — for example, what to do if IAM credentials are compromised, if an EC2 instance is behaving suspiciously, or if CUI is found in a publicly accessible S3 bucket? Are GuardDuty and Security Hub integrated into your detection workflow?"
        },
    ],
    "IR.L2-3.6.2": [
        {
            "question": "How do you track and document incidents from detection through resolution? Do you use a ticketing system, incident management platform, or documented log? Are incidents reported to the appropriate internal officials and, when required, to DIBCAC or the DoD?"
        },
    ],
    "IR.L2-3.6.3": [
        {
            "question": "How often do you test your incident response capability — through tabletop exercises, simulations, or live drills? When was the last test, and did it include a scenario involving CUI compromise in your AWS environment?"
        },
    ],

    # =========================================================================
    # MA — Maintenance
    # =========================================================================

    "MA.L2-3.7.1": [
        {
            "question": "How do you schedule and perform maintenance on systems that handle CUI — patching, updates, hardware repairs? Is there a documented maintenance schedule, and are maintenance windows communicated to stakeholders?"
        },
        {
            "question": "In AWS, are you using Systems Manager Patch Manager for automated patching of EC2 instances? Do you have maintenance windows defined that minimize disruption to CUI processing?"
        },
    ],
    "MA.L2-3.7.2": [
        {
            "question": "How do you control the tools and techniques used for system maintenance? For example, are maintenance tools (like remote access software, diagnostic utilities) approved, inventoried, and checked for integrity before use?"
        },
    ],
    "MA.L2-3.7.3": [
        {
            "question": "When equipment that has processed CUI is sent off-site for repair or maintenance, how do you ensure all CUI is removed first? Do you sanitize storage media, or remove and retain storage devices before shipping equipment out?"
        },
    ],
    "MA.L2-3.7.4": [
        {
            "question": "Before using diagnostic or test media (USB drives, CDs, downloaded tools) on CUI systems, do you scan them for malware? What scanning tools do you use, and is this step documented in your maintenance procedures?"
        },
    ],
    "MA.L2-3.7.5": [
        {
            "question": "When maintenance is performed remotely (over the network rather than physically at the machine), is MFA required to establish the session? Is the remote maintenance session terminated when the work is done, rather than left open?"
        },
    ],
    "MA.L2-3.7.6": [
        {
            "question": "When external maintenance personnel (vendors, contractors) who don't have authorization to access CUI perform maintenance, are they supervised by authorized staff? How do you ensure they can't access CUI during their work?"
        },
    ],

    # =========================================================================
    # MP — Media Protection
    # =========================================================================

    "MP.L2-3.8.1": [
        {
            "question": "How do you physically secure media (hard drives, USB drives, backup tapes, printed documents) that contain CUI? Are they stored in locked cabinets, safes, or controlled-access rooms when not in use?"
        },
    ],
    "MP.L2-3.8.2": [
        {
            "question": "How do you restrict who can access media containing CUI? Is there an access list for storage locations, and are access attempts logged? For digital media in AWS, are S3 bucket policies and IAM roles restricting access to only authorized users?"
        },
    ],
    "MP.L2-3.8.3": [
        {
            "question": "Before disposing of or reusing media that contained CUI, how do you sanitize it? Do you use NIST SP 800-88 guidelines — for example, cryptographic erase for SSDs, degaussing for magnetic media, or physical destruction? For AWS, do you rely on AWS's media sanitization processes (documented in SOC reports)?"
        },
    ],
    "MP.L2-3.8.4": [
        {
            "question": "Are media containing CUI properly marked with CUI markings and distribution limitations? For example, do printed documents have CUI banners, and do digital files or folders have clear CUI labels?"
        },
    ],
    "MP.L2-3.8.5": [
        {
            "question": "When CUI media is transported outside your controlled environment — for example, shipping backup tapes or carrying a laptop to another facility — how do you maintain control and accountability? Is there a chain-of-custody process?"
        },
    ],
    "MP.L2-3.8.6": [
        {
            "question": "When digital media containing CUI is transported (e.g., shipping an encrypted hard drive to a partner), is the data encrypted? What encryption standard do you use — AES-256, FIPS 140-2 validated modules? Or do you use alternative physical safeguards like tamper-evident packaging and courier services?"
        },
    ],
    "MP.L2-3.8.7": [
        {
            "question": "How do you control the use of removable media (USB drives, external hard drives, SD cards) on systems that process CUI? Are USB ports disabled by default, with exceptions granted only for approved devices?"
        },
    ],
    "MP.L2-3.8.8": [
        {
            "question": "Do you prohibit the use of personally-owned or unidentified portable storage devices on CUI systems? For example, if someone finds a USB drive in the parking lot, is there a policy preventing them from plugging it into a work computer?"
        },
    ],
    "MP.L2-3.8.9": [
        {
            "question": "How do you protect backup copies of CUI? Are backups encrypted at rest (for example, using AWS Backup with KMS encryption), stored in a separate account or region, and access-restricted to backup administrators only?"
        },
    ],

    # =========================================================================
    # PE — Physical Protection
    # =========================================================================

    "PE.L2-3.10.1": [
        {
            "question": "How do you control physical access to facilities, server rooms, and workstations where CUI is processed or stored? Do you use badge readers, biometric scanners, or key locks? Who authorizes physical access?"
        },
    ],
    "PE.L2-3.10.2": [
        {
            "question": "How do you monitor the physical facility — security cameras, intrusion detection systems, security guards? Are server rooms and network closets monitored 24/7? For AWS infrastructure, are you relying on AWS's physical security controls (documented in SOC 2 reports)?"
        },
    ],
    "PE.L2-3.10.3": [
        {
            "question": "How do you handle visitors to areas where CUI is accessible? Are visitors required to sign in, wear badges, and be escorted at all times? Is visitor activity logged?"
        },
    ],
    "PE.L2-3.10.4": [
        {
            "question": "Do you maintain logs of who enters and exits areas where CUI systems are located? How long are these logs retained, and who reviews them? Are badge reader logs or sign-in sheets available for assessor review?"
        },
    ],
    "PE.L2-3.10.5": [
        {
            "question": "How do you manage physical access devices — keys, badges, access cards, combinations? Is there a process for issuing, tracking, and revoking them when someone leaves or changes roles?"
        },
    ],
    "PE.L2-3.10.6": [
        {
            "question": "When employees work from home or other alternate locations with CUI, what safeguards are in place? For example, are they required to use encrypted laptops, VPN connections, and private workspaces where screens aren't visible to unauthorized people?"
        },
    ],

    # =========================================================================
    # PS — Personnel Security
    # =========================================================================

    "PS.L2-3.9.1": [
        {
            "question": "What background screening do you perform before granting someone access to CUI systems? Does it include criminal background checks, employment verification, and reference checks? Are screenings repeated periodically?"
        },
    ],
    "PS.L2-3.9.2": [
        {
            "question": "When an employee is terminated or transfers to a different role, how quickly is their access to CUI systems revoked? Is there a documented offboarding checklist that includes disabling accounts, revoking badges, collecting equipment, and removing IAM access?"
        },
        {
            "question": "For AWS access specifically, how quickly are IAM users disabled, SSO sessions terminated, and access keys deactivated when someone leaves? Is this automated through your identity provider, or is it a manual process?"
        },
    ],

    # =========================================================================
    # RA — Risk Assessment
    # =========================================================================

    "RA.L2-3.11.1": [
        {
            "question": "How often do you perform risk assessments of your CUI environment? Is it at least annually, plus whenever there are significant changes? Does the assessment cover threats to CUI confidentiality, integrity, and availability?"
        },
        {
            "question": "Does your risk assessment include your AWS environment — for example, evaluating risks from misconfigured S3 buckets, overly permissive IAM policies, unencrypted data stores, or insufficient logging? Do you use Security Hub findings or Inspector results as inputs to your risk assessment?"
        },
    ],
    "RA.L2-3.11.2": [
        {
            "question": "How do you scan for vulnerabilities in your systems and applications? Are you using Amazon Inspector for EC2 and container scanning, running authenticated vulnerability scans on your network, and scanning web applications for OWASP Top 10 issues?"
        },
        {
            "question": "How often do you scan — continuously, weekly, monthly? When a new critical vulnerability is announced (like a Log4j-level event), how quickly can you scan your environment to determine if you're affected?"
        },
    ],
    "RA.L2-3.11.3": [
        {
            "question": "Once vulnerabilities are identified, how do you prioritize and remediate them? Do you have defined timelines — for example, critical vulnerabilities patched within 48 hours, high within 30 days? How do you track remediation progress?"
        },
    ],

    # =========================================================================
    # CA — Security Assessment
    # =========================================================================

    "CA.L2-3.12.1": [
        {
            "question": "How often do you assess whether your security controls are actually working as intended? Do you perform periodic control testing — for example, verifying that encryption is enabled, access controls are enforced, and logging is functioning?"
        },
        {
            "question": "In AWS, are you using Security Hub compliance scores, AWS Config conformance packs, or AWS Audit Manager assessments to continuously evaluate control effectiveness?"
        },
    ],
    "CA.L2-3.12.2": [
        {
            "question": "When you identify security deficiencies or vulnerabilities, do you create a formal Plan of Action and Milestones (POA&M) to track remediation? Does each item have an owner, target date, and status? CMMC assessors will want to see your POA&M."
        },
    ],
    "CA.L2-3.12.3": [
        {
            "question": "How do you continuously monitor your security controls rather than just checking them periodically? For example, are AWS Config rules running continuously, is Security Hub aggregating findings in real time, and are GuardDuty and Inspector providing ongoing monitoring?"
        },
    ],
    "CA.L2-3.12.4": [
        {
            "question": "Do you have a System Security Plan (SSP) that describes your CUI environment — system boundaries, how each CMMC practice is implemented, connections to other systems, and the operating environment? Is it kept up to date as your environment changes?"
        },
        {
            "question": "Does your SSP cover your AWS environment specifically — VPC architecture, account structure, data flow diagrams showing where CUI resides, and how AWS services implement each security requirement?"
        },
    ],

    # =========================================================================
    # SC — System and Communications Protection
    # =========================================================================

    "SC.L2-3.13.1": [
        {
            "question": "How do you monitor and protect communications at your network boundaries? For example, do you use AWS Network Firewall, WAF, or third-party firewalls at VPC boundaries? Are VPC Flow Logs enabled and analyzed for suspicious traffic?"
        },
        {
            "question": "What about internal boundaries — do you segment your CUI environment from other parts of your network using separate VPCs, subnets, or security groups? Can you walk us through your network architecture?"
        },
    ],
    "SC.L2-3.13.2": [
        {
            "question": "How does your system architecture promote security? For example, do you use defense-in-depth principles — multiple layers of security controls, separation of components, fail-secure design? In AWS, do you follow the Well-Architected Framework security pillar?"
        },
    ],
    "SC.L2-3.13.3": [
        {
            "question": "Is user-facing functionality (web applications, portals) separated from system management functionality (admin consoles, configuration interfaces)? For example, are management interfaces on separate subnets or VPCs, accessible only through bastion hosts or VPN?"
        },
    ],
    "SC.L2-3.13.4": [
        {
            "question": "How do you prevent information from leaking between users or processes through shared system resources — like shared memory, temporary files, or database connection pools? In AWS, are you using dedicated tenancy for sensitive workloads, or have you evaluated the isolation provided by standard EC2 instances?"
        },
    ],
    "SC.L2-3.13.5": [
        {
            "question": "Are your publicly accessible components (web servers, load balancers, API gateways) in a separate subnet or VPC from your internal systems? In AWS, do you use public subnets for ALBs/CloudFront and private subnets for application servers and databases?"
        },
    ],
    "SC.L2-3.13.6": [
        {
            "question": "Is your network configured to deny all traffic by default and only allow what's explicitly needed? For example, do your security groups start with no inbound rules and add only required ports? Do your NACLs follow a deny-all-permit-by-exception approach?"
        },
    ],
    "SC.L2-3.13.7": [
        {
            "question": "Do you prevent split tunneling on VPN connections — meaning when a user is connected to your network via VPN, all their traffic goes through the VPN rather than some going directly to the internet? How is this enforced in your VPN configuration?"
        },
    ],
    "SC.L2-3.13.8": [
        {
            "question": "Is CUI encrypted whenever it's transmitted — whether over the internet, between AWS services, or across your internal network? Are you using TLS 1.2 or higher for all communications? Are S3 bucket policies requiring aws:SecureTransport?"
        },
        {
            "question": "For connections between your on-premises environment and AWS, are you using Site-to-Site VPN with IPsec encryption or AWS Direct Connect with MACsec encryption?"
        },
    ],
    "SC.L2-3.13.9": [
        {
            "question": "Do network connections automatically terminate after a session ends or after a defined period of inactivity? For example, do idle SSH sessions time out after 15 minutes, and do load balancer connections have appropriate idle timeout settings?"
        },
    ],
    "SC.L2-3.13.10": [
        {
            "question": "How do you manage cryptographic keys — creation, distribution, storage, rotation, and destruction? In AWS, are you using KMS for key management with automatic annual rotation enabled? Who has access to manage KMS keys, and is that access audited?"
        },
    ],
    "SC.L2-3.13.11": [
        {
            "question": "When cryptography is used to protect CUI, is it FIPS 140-2 validated? In AWS, are you using FIPS endpoints for API calls and KMS keys backed by FIPS 140-2 Level 2 validated HSMs? For on-premises systems, are your encryption modules FIPS validated?"
        },
    ],
    "SC.L2-3.13.12": [
        {
            "question": "Do you have collaborative computing devices (video conferencing systems, smart displays, shared screens) in areas where CUI is discussed? Can they be remotely activated without the user knowing? Is there a visible indicator (like a light) when cameras or microphones are active?"
        },
    ],
    "SC.L2-3.13.13": [
        {
            "question": "How do you control mobile code — JavaScript, Java applets, ActiveX controls, macros — on systems that process CUI? Do you have policies restricting which mobile code technologies are allowed, and do you block unsigned or untrusted code?"
        },
    ],
    "SC.L2-3.13.14": [
        {
            "question": "If you use Voice over IP (VoIP) for calls that may involve CUI discussions, how do you protect those communications? Is VoIP traffic encrypted, segmented from data traffic, and monitored? Are you using Amazon Chime or another approved platform?"
        },
    ],
    "SC.L2-3.13.15": [
        {
            "question": "How do you protect the authenticity of communication sessions — ensuring you're actually talking to the right server or person, not an impersonator? Are you using TLS with certificate validation, mutual TLS for service-to-service communication, or DNSSEC?"
        },
    ],
    "SC.L2-3.13.16": [
        {
            "question": "Is CUI encrypted at rest — on hard drives, in databases, in S3 buckets, on backup media? In AWS, are you using KMS-managed encryption for S3, EBS, RDS, DynamoDB, and other storage services? Are there AWS Config rules verifying encryption is enabled?"
        },
        {
            "question": "For on-premises systems, are hard drives encrypted with BitLocker, LUKS, or similar full-disk encryption? Are database-level encryption features enabled for databases containing CUI?"
        },
    ],

    # =========================================================================
    # SI — System and Information Integrity
    # =========================================================================

    "SI.L2-3.14.1": [
        {
            "question": "How do you identify, report, and fix system flaws (bugs, vulnerabilities, misconfigurations) in a timely manner? Do you have a patch management process with defined timelines — for example, critical patches within 48 hours, high within 30 days?"
        },
        {
            "question": "In AWS, are you using Systems Manager Patch Manager for automated patching, Inspector for vulnerability identification, and Config rules to detect misconfigurations? How do you track remediation from finding to fix?"
        },
    ],
    "SI.L2-3.14.2": [
        {
            "question": "What malware protection do you have on systems that process CUI? Is antivirus/anti-malware installed on all endpoints, servers, and email gateways? In AWS, is GuardDuty Malware Protection enabled for EC2 and EBS scanning?"
        },
    ],
    "SI.L2-3.14.3": [
        {
            "question": "How do you stay informed about security alerts and advisories — from vendors, CISA, US-CERT, AWS Security Bulletins? When a critical advisory comes out, what's your process for evaluating whether it affects your CUI environment and taking action?"
        },
    ],
    "SI.L2-3.14.4": [
        {
            "question": "How quickly do you update malware protection signatures and engines when new versions are released? Is this automatic, or does someone need to manually approve and push updates? What's the typical lag between vendor release and deployment to your CUI systems?"
        },
    ],
    "SI.L2-3.14.5": [
        {
            "question": "Do you perform both periodic full-system scans and real-time scanning of files as they're downloaded, opened, or executed? How often are full scans run — daily, weekly? Are files from external sources (email attachments, USB drives, downloads) scanned before they can be accessed?"
        },
    ],
    "SI.L2-3.14.6": [
        {
            "question": "How do you monitor your systems for attacks and indicators of potential attacks? Are you watching both inbound and outbound traffic? In AWS, are GuardDuty, VPC Flow Logs, and CloudTrail all feeding into a monitoring solution that can detect anomalous patterns?"
        },
        {
            "question": "Do you have alerting set up for indicators of compromise — like unusual outbound data transfers, connections to known-bad IP addresses, or unexpected API calls? What tools do you use to correlate these signals — Security Hub, a SIEM, Amazon Detective?"
        },
    ],
    "SI.L2-3.14.7": [
        {
            "question": "How do you detect unauthorized use of your systems — for example, someone using a system account for purposes outside their job role, or an unauthorized application running on a CUI system? Do you baseline normal behavior and alert on deviations?"
        },
    ],
}

# =========================================================================
# CMMC Level 2 practice-specific evidence questions
# Each practice maps to a string describing the specific evidence artifacts
# an assessor would expect to see. These guide the advisor toward specific,
# auditable evidence artifacts for CMMC Level 2 assessment.
# =========================================================================
CMMC_EVIDENCE_QUESTIONS: Dict[str, str] = {

    # AC — Access Control
    "AC.L2-3.1.1": "Provide: (1) Access control policy defining authorized users, processes, and devices, (2) IAM Identity Center or IdP configuration showing user provisioning, (3) IAM policies demonstrating access restrictions to CUI systems, (4) Access authorization records showing approval process for new access.",
    "AC.L2-3.1.2": "Provide: (1) Role-based access control (RBAC) matrix showing roles and permitted functions, (2) IAM policies demonstrating function-level restrictions, (3) Application-level access control configurations, (4) Evidence of periodic access reviews validating role assignments.",
    "AC.L2-3.1.3": "Provide: (1) Data flow diagrams showing approved CUI flow paths, (2) Network segmentation evidence (VPC configurations, security groups, NACLs), (3) S3 bucket policies or DLP rules controlling CUI movement, (4) Firewall rules enforcing approved data flows.",
    "AC.L2-3.1.4": "Provide: (1) Separation of duties matrix identifying incompatible roles, (2) IAM policies showing role separation (e.g., separate deploy vs. approve roles), (3) Evidence that no single individual can perform all critical steps of sensitive processes.",
    "AC.L2-3.1.5": "Provide: (1) Least privilege policy documentation, (2) IAM policies showing scoped permissions (no wildcard actions), (3) IAM Access Analyzer findings showing unused permissions identified and removed, (4) Privileged account inventory with MFA enforcement evidence.",
    "AC.L2-3.1.6": "Provide: (1) Policy requiring non-privileged accounts for non-security functions, (2) Evidence of separate admin and standard user accounts for administrators, (3) IAM role configurations showing separate privileged and non-privileged roles.",
    "AC.L2-3.1.7": "Provide: (1) IAM policies denying privileged actions for non-privileged roles, (2) CloudTrail logs showing denied privilege escalation attempts are captured, (3) Alerting configuration for unauthorized privileged function execution attempts.",
    "AC.L2-3.1.8": "Provide: (1) Account lockout policy with defined thresholds (e.g., 3-5 attempts), (2) Identity provider lockout configuration screenshots, (3) CloudWatch alarms or GuardDuty findings for brute-force detection, (4) Evidence of lockout testing.",
    "AC.L2-3.1.9": "Provide: (1) System use notification policy, (2) Screenshots of login banners on CUI systems (consoles, VPN portals, bastion hosts, WorkSpaces), (3) Banner text content showing authorized use, monitoring, and consent language.",
    "AC.L2-3.1.10": "Provide: (1) Session lock policy with defined inactivity timeout (e.g., 15 minutes), (2) Group Policy or MDM configuration enforcing screen lock, (3) WorkSpaces or remote desktop timeout settings, (4) Evidence that lock screens conceal CUI content.",
    "AC.L2-3.1.11": "Provide: (1) Session termination policy with defined conditions, (2) Application and system timeout configurations, (3) Load balancer idle timeout settings, (4) SSH and RDP session timeout configurations.",
    "AC.L2-3.1.12": "Provide: (1) Remote access policy, (2) VPN or Systems Manager Session Manager configuration and logs, (3) Remote session monitoring dashboard or log analysis reports, (4) Evidence of remote access session review procedures.",
    "AC.L2-3.1.13": "Provide: (1) VPN configuration showing encryption protocols (IPsec, TLS), (2) SSH configuration showing strong cipher suites, (3) TLS certificate configurations for remote access portals, (4) Site-to-Site VPN or Direct Connect encryption evidence.",
    "AC.L2-3.1.14": "Provide: (1) Network architecture diagram showing managed access control points, (2) VPN concentrator or Client VPN endpoint configuration, (3) Evidence that direct connections bypassing access control points are blocked.",
    "AC.L2-3.1.15": "Provide: (1) Policy defining who can execute privileged commands remotely, (2) Authorization records for remote privileged access, (3) Audit logs of remote privileged command execution.",
    "AC.L2-3.1.16": "Provide: (1) Wireless access authorization policy, (2) Approved wireless device inventory, (3) Wireless access point configuration showing authentication requirements, (4) Rogue AP detection scan results.",
    "AC.L2-3.1.17": "Provide: (1) Wireless security configuration showing WPA2-Enterprise or WPA3, (2) 802.1X authentication configuration, (3) Wireless network segmentation evidence separating CUI-accessible networks.",
    "AC.L2-3.1.18": "Provide: (1) Mobile device policy, (2) MDM enrollment and compliance reports, (3) Device encryption and screen lock enforcement evidence, (4) Remote wipe capability documentation.",
    "AC.L2-3.1.19": "Provide: (1) Mobile device encryption policy, (2) MDM reports showing encryption status on enrolled devices, (3) BitLocker/FileVault configuration for laptops, (4) Lost device response procedures.",
    "AC.L2-3.1.20": "Provide: (1) External system connection policy, (2) Interconnection security agreements (ISAs) with external partners, (3) VPC peering or Transit Gateway configurations for external connections, (4) Security group rules restricting external system access.",
    "AC.L2-3.1.21": "Provide: (1) Portable storage device policy, (2) USB device control configuration (Group Policy, endpoint protection), (3) Evidence of enforcement (blocked device logs), (4) Approved portable storage device inventory if exceptions exist.",
    "AC.L2-3.1.22": "Provide: (1) Policy prohibiting CUI on publicly accessible systems, (2) S3 Block Public Access configuration, (3) AWS Config rules for S3_BUCKET_PUBLIC_READ_PROHIBITED and S3_BUCKET_PUBLIC_WRITE_PROHIBITED, (4) Amazon Macie scan results for publicly accessible buckets, (5) Content review procedures for public-facing systems.",

    # AT — Awareness and Training
    "AT.L2-3.2.1": "Provide: (1) Security awareness training policy with frequency requirements, (2) Training curriculum covering CUI handling, phishing, social engineering, (3) Training completion records with dates and percentages, (4) Follow-up records for non-completions.",
    "AT.L2-3.2.2": "Provide: (1) Role-based training curriculum for security-related roles, (2) Training completion records for system administrators, security analysts, and incident responders, (3) AWS-specific training records (IAM, CloudTrail, GuardDuty) for cloud administrators.",
    "AT.L2-3.2.3": "Provide: (1) Insider threat awareness training materials, (2) Training completion records, (3) Insider threat reporting procedures and contact information, (4) Non-retaliation policy documentation.",

    # AU — Audit and Accountability
    "AU.L2-3.3.1": "Provide: (1) Audit logging policy defining auditable events, (2) CloudTrail configuration showing multi-region, management and data events, (3) Application-level audit log configurations, (4) Log retention policy and evidence of retention periods (S3 lifecycle, CloudWatch retention settings).",
    "AU.L2-3.3.2": "Provide: (1) Policy prohibiting shared accounts, (2) IAM credential report showing individual user accounts, (3) Identity provider configuration showing unique user identification, (4) CloudTrail log samples showing individual user attribution for API calls.",
    "AU.L2-3.3.3": "Provide: (1) Audit event review schedule and records, (2) Evidence of logging configuration updates when new systems or services are deployed, (3) Change records showing audit logging scope adjustments.",
    "AU.L2-3.3.4": "Provide: (1) Audit logging failure alerting configuration, (2) CloudWatch alarms for CloudTrail status changes, (3) SCP preventing CloudTrail disablement, (4) Evidence of alert testing and response procedures.",
    "AU.L2-3.3.5": "Provide: (1) Log correlation procedures or SIEM configuration, (2) CloudWatch Logs Insights or Athena query examples used for investigation, (3) Amazon Detective investigation examples, (4) Sample correlation analysis from a recent security event.",
    "AU.L2-3.3.6": "Provide: (1) Audit report generation capability demonstration, (2) Sample reports (access reports, change reports, compliance reports), (3) Athena or SIEM query examples for on-demand analysis, (4) Security Hub dashboard screenshots.",
    "AU.L2-3.3.7": "Provide: (1) Time synchronization policy, (2) NTP configuration on servers and network devices, (3) Evidence EC2 instances use Amazon Time Sync Service, (4) Time synchronization monitoring and alerting configuration.",
    "AU.L2-3.3.8": "Provide: (1) Audit log protection policy, (2) S3 bucket configuration for CloudTrail logs showing Object Lock or versioning, (3) IAM policies restricting log access to security team, (4) Separate logging account configuration in AWS Organizations.",
    "AU.L2-3.3.9": "Provide: (1) Policy restricting audit logging management to privileged users, (2) IAM policies showing only security administrators can modify CloudTrail, CloudWatch, or logging configurations, (3) SCP preventing non-admin modification of logging resources.",

    # CM — Configuration Management
    "CM.L2-3.4.1": "Provide: (1) Baseline configuration documentation for CUI systems, (2) AWS Config resource inventory, (3) Systems Manager Inventory reports, (4) Hardware and software inventory with version tracking, (5) Configuration management plan.",
    "CM.L2-3.4.2": "Provide: (1) Security configuration standards (CIS Benchmarks, STIG, custom hardening guides), (2) Security Hub compliance reports for CIS or FSBP standards, (3) AWS Config rule compliance reports, (4) Evidence of automated enforcement or remediation of configuration deviations.",
    "CM.L2-3.4.3": "Provide: (1) Change management policy and procedures, (2) Change request records with approval workflows, (3) CloudFormation or CDK version control history, (4) CloudTrail logs showing configuration changes with user attribution.",
    "CM.L2-3.4.4": "Provide: (1) Security impact analysis procedures for changes, (2) Change request records showing security review step, (3) Examples of security impact assessments performed before changes to CUI systems.",
    "CM.L2-3.4.5": "Provide: (1) Access control policy for change management, (2) IAM roles restricting who can modify CUI system configurations, (3) Physical access controls for on-premises equipment changes, (4) Change approval records showing authorized personnel.",
    "CM.L2-3.4.6": "Provide: (1) Least functionality policy, (2) Evidence of unnecessary services disabled on CUI systems, (3) SCPs restricting unused AWS services, (4) System hardening checklists showing non-essential capabilities removed.",
    "CM.L2-3.4.7": "Provide: (1) Port, protocol, and service restriction policy, (2) Security group configurations showing only required ports, (3) Network scan results confirming only approved ports are open, (4) Firewall rules blocking non-essential protocols.",
    "CM.L2-3.4.8": "Provide: (1) Application whitelisting or blacklisting policy, (2) AppLocker or application control configuration evidence, (3) Approved software list, (4) Evidence of enforcement (blocked execution logs).",
    "CM.L2-3.4.9": "Provide: (1) User-installed software policy, (2) Endpoint management configuration restricting software installation, (3) Software inventory reports showing user-installed applications, (4) Monitoring logs for unauthorized software installations.",

    # IA — Identification and Authentication
    "IA.L2-3.5.1": "Provide: (1) User identification policy, (2) User account inventory showing unique identifiers, (3) Service account inventory, (4) Device identification records (certificates, MAC addresses, or asset tags).",
    "IA.L2-3.5.2": "Provide: (1) Authentication policy defining approved methods, (2) Identity provider configuration, (3) IAM Identity Center or federation setup documentation, (4) Authentication mechanism testing records.",
    "IA.L2-3.5.3": "Provide: (1) MFA policy requiring MFA for privileged and network access, (2) IAM credential report showing MFA enabled for all users, (3) Identity Center MFA configuration, (4) VPN MFA configuration, (5) Root account MFA evidence.",
    "IA.L2-3.5.4": "Provide: (1) Authentication mechanism documentation showing replay resistance (TOTP, challenge-response), (2) Protocol configuration evidence (Kerberos, SAML with anti-replay), (3) Network authentication configuration.",
    "IA.L2-3.5.5": "Provide: (1) Identifier reuse policy with defined waiting period, (2) Identity provider configuration showing reuse prevention, (3) Process documentation for identifier lifecycle management.",
    "IA.L2-3.5.6": "Provide: (1) Inactive account policy with defined inactivity period, (2) IAM credential report showing last-used dates, (3) Automated account disablement configuration, (4) IAM Access Analyzer or custom reports identifying stale accounts.",
    "IA.L2-3.5.7": "Provide: (1) Password policy with complexity requirements, (2) Identity provider password policy configuration screenshots, (3) IAM account password policy configuration, (4) Evidence requirements meet or exceed DoD standards.",
    "IA.L2-3.5.8": "Provide: (1) Password history policy with defined generations, (2) Identity provider configuration showing password history enforcement, (3) IAM password policy showing reuse prevention setting.",
    "IA.L2-3.5.9": "Provide: (1) Temporary password policy requiring immediate change, (2) Identity provider configuration enforcing password change on first login, (3) Secure temporary password delivery procedures.",
    "IA.L2-3.5.10": "Provide: (1) Password storage policy requiring cryptographic protection, (2) Evidence of hashing algorithms used (bcrypt, PBKDF2), (3) TLS configuration for password transmission, (4) Secrets Manager or Parameter Store usage for application credentials.",
    "IA.L2-3.5.11": "Provide: (1) Authentication feedback policy, (2) Screenshots showing password masking on login screens, (3) Application configuration for input masking on authentication fields.",

    # IR — Incident Response
    "IR.L2-3.6.1": "Provide: (1) Incident response plan covering preparation, detection, analysis, containment, eradication, recovery, (2) CUI-specific incident procedures, (3) AWS-specific runbooks (compromised credentials, S3 exposure, unauthorized EC2), (4) GuardDuty and Security Hub integration documentation, (5) Incident response team roster with contact information.",
    "IR.L2-3.6.2": "Provide: (1) Incident tracking system or log, (2) Sample incident reports showing documentation from detection through resolution, (3) Reporting procedures for internal officials and external authorities (DIBCAC, DoD), (4) Evidence of incident reporting for recent events.",
    "IR.L2-3.6.3": "Provide: (1) Incident response test schedule, (2) Tabletop exercise or simulation records with dates and participants, (3) After-action reports from exercises, (4) Plan updates made based on exercise findings.",

    # MA — Maintenance
    "MA.L2-3.7.1": "Provide: (1) Maintenance policy and schedule, (2) Systems Manager Patch Manager configuration and compliance reports, (3) Maintenance window documentation, (4) Maintenance records showing completed activities.",
    "MA.L2-3.7.2": "Provide: (1) Approved maintenance tools inventory, (2) Tool integrity verification procedures, (3) Maintenance tool access controls, (4) Records of tool usage during maintenance activities.",
    "MA.L2-3.7.3": "Provide: (1) Media sanitization procedures for off-site maintenance, (2) Records of sanitization performed before equipment left the facility, (3) NIST SP 800-88 compliance documentation for sanitization methods.",
    "MA.L2-3.7.4": "Provide: (1) Diagnostic media scanning procedures, (2) Malware scan records for maintenance media before use, (3) Approved diagnostic tool list.",
    "MA.L2-3.7.5": "Provide: (1) Remote maintenance policy requiring MFA, (2) MFA configuration for remote maintenance sessions, (3) Session termination procedures and evidence, (4) Remote maintenance session logs.",
    "MA.L2-3.7.6": "Provide: (1) Maintenance personnel supervision policy, (2) Escort and supervision logs for unauthorized maintenance personnel, (3) Access restrictions preventing maintenance personnel from accessing CUI during supervised sessions.",

    # MP — Media Protection
    "MP.L2-3.8.1": "Provide: (1) Media protection policy, (2) Physical storage security evidence (locked cabinets, controlled-access rooms), (3) Digital media access controls, (4) Media inventory and tracking records.",
    "MP.L2-3.8.2": "Provide: (1) Media access authorization policy, (2) Access lists for media storage locations, (3) S3 bucket policies and IAM roles restricting CUI media access, (4) Access log records for media storage areas.",
    "MP.L2-3.8.3": "Provide: (1) Media sanitization policy referencing NIST SP 800-88, (2) Sanitization records with method used, date, and personnel, (3) Destruction certificates for physically destroyed media, (4) AWS SOC reports documenting AWS media sanitization for cloud resources.",
    "MP.L2-3.8.4": "Provide: (1) CUI marking policy, (2) Examples of marked media (documents with CUI banners, labeled storage devices), (3) Distribution limitation markings on CUI materials.",
    "MP.L2-3.8.5": "Provide: (1) Media transport policy, (2) Chain-of-custody forms or tracking records, (3) Approved transport methods documentation, (4) Accountability records for media during transport.",
    "MP.L2-3.8.6": "Provide: (1) Digital media transport encryption policy, (2) Encryption configuration evidence (AES-256, FIPS 140-2 validated), (3) Alternative physical safeguard documentation if encryption is not used.",
    "MP.L2-3.8.7": "Provide: (1) Removable media policy, (2) USB device control configuration (Group Policy, endpoint protection), (3) Approved removable media inventory, (4) Enforcement logs showing blocked unauthorized devices.",
    "MP.L2-3.8.8": "Provide: (1) Policy prohibiting unidentified portable storage devices, (2) Training materials covering this requirement, (3) Endpoint protection configuration blocking unknown USB devices.",
    "MP.L2-3.8.9": "Provide: (1) Backup CUI protection policy, (2) AWS Backup configuration with KMS encryption, (3) Backup storage access controls (separate account, restricted IAM roles), (4) Backup Vault Lock configuration if applicable.",

    # PE — Physical Protection
    "PE.L2-3.10.1": "Provide: (1) Physical access control policy, (2) Access control system configuration (badge readers, biometrics), (3) Authorized access lists for CUI areas, (4) Physical access authorization records.",
    "PE.L2-3.10.2": "Provide: (1) Physical monitoring policy, (2) Security camera placement documentation, (3) Intrusion detection system configuration, (4) AWS SOC 2 reports for AWS data center physical security, (5) Monitoring review records.",
    "PE.L2-3.10.3": "Provide: (1) Visitor management policy, (2) Visitor sign-in logs, (3) Escort procedures documentation, (4) Visitor badge issuance and return records.",
    "PE.L2-3.10.4": "Provide: (1) Physical access logging policy with retention requirements, (2) Badge reader or sign-in log records, (3) Log review records, (4) Sample audit logs covering the required retention period.",
    "PE.L2-3.10.5": "Provide: (1) Physical access device management policy, (2) Key/badge/card inventory, (3) Issuance and revocation records, (4) Periodic inventory reconciliation records.",
    "PE.L2-3.10.6": "Provide: (1) Alternate work site security policy, (2) Telework agreement templates with security requirements, (3) VPN and encrypted laptop requirements for remote CUI access, (4) Signed telework agreements.",

    # PS — Personnel Security
    "PS.L2-3.9.1": "Provide: (1) Personnel screening policy, (2) Background check procedures and completion records, (3) Screening criteria documentation, (4) Re-screening schedule if applicable.",
    "PS.L2-3.9.2": "Provide: (1) Personnel termination and transfer procedures, (2) Offboarding checklist including access revocation steps, (3) IAM user disablement records correlated with HR termination dates, (4) Equipment return records, (5) Badge/key revocation records.",

    # RA — Risk Assessment
    "RA.L2-3.11.1": "Provide: (1) Risk assessment policy with frequency requirements, (2) Most recent risk assessment report covering CUI environment, (3) Risk register with identified threats and risk ratings, (4) Security Hub or Inspector findings used as risk assessment inputs.",
    "RA.L2-3.11.2": "Provide: (1) Vulnerability scanning policy with frequency requirements, (2) Amazon Inspector scan configuration and recent reports, (3) Network vulnerability scan results, (4) Web application scan results, (5) Vulnerability tracking and remediation records.",
    "RA.L2-3.11.3": "Provide: (1) Vulnerability remediation policy with defined timelines by severity, (2) Remediation tracking records showing timelines met, (3) Risk acceptance documentation for vulnerabilities not remediated within timelines, (4) Patch compliance reports.",

    # CA — Security Assessment
    "CA.L2-3.12.1": "Provide: (1) Security control assessment policy with frequency, (2) Assessment reports showing control testing results, (3) Security Hub compliance scores, (4) AWS Config conformance pack results, (5) AWS Audit Manager assessment reports.",
    "CA.L2-3.12.2": "Provide: (1) Plan of Action and Milestones (POA&M) document, (2) POA&M entries with owners, target dates, and status, (3) Evidence of POA&M review and updates, (4) Closed POA&M items with completion evidence.",
    "CA.L2-3.12.3": "Provide: (1) Continuous monitoring strategy document, (2) AWS Config continuous rule evaluation evidence, (3) Security Hub real-time finding aggregation, (4) GuardDuty and Inspector continuous monitoring configuration, (5) Monitoring dashboard screenshots.",
    "CA.L2-3.12.4": "Provide: (1) System Security Plan (SSP) document, (2) SSP sections covering system boundaries, environment description, security implementation, (3) Network and data flow diagrams, (4) SSP version history showing periodic updates, (5) AWS environment architecture documentation within the SSP.",

    # SC — System and Communications Protection
    "SC.L2-3.13.1": "Provide: (1) Boundary protection policy, (2) Network architecture diagram showing external and internal boundaries, (3) AWS Network Firewall, WAF, or security group configurations at boundaries, (4) VPC Flow Log analysis reports, (5) Boundary monitoring dashboard screenshots.",
    "SC.L2-3.13.2": "Provide: (1) Security architecture documentation, (2) Defense-in-depth design evidence, (3) AWS Well-Architected Framework security pillar review results, (4) Secure development practices documentation.",
    "SC.L2-3.13.3": "Provide: (1) Architecture documentation showing user/management function separation, (2) Separate subnets or VPCs for management interfaces, (3) Bastion host or VPN-only access to management functions, (4) Network diagrams showing separation.",
    "SC.L2-3.13.4": "Provide: (1) Shared resource protection policy, (2) EC2 dedicated tenancy configuration if used, (3) Application-level isolation controls, (4) Memory and storage isolation documentation.",
    "SC.L2-3.13.5": "Provide: (1) Network architecture showing DMZ or public subnet separation, (2) VPC subnet configurations (public vs. private), (3) ALB/CloudFront in public subnets with application servers in private subnets, (4) Security group rules enforcing separation.",
    "SC.L2-3.13.6": "Provide: (1) Deny-by-default network policy, (2) Security group configurations starting from deny-all, (3) NACL configurations with explicit deny rules, (4) Firewall rules demonstrating deny-all-permit-by-exception approach.",
    "SC.L2-3.13.7": "Provide: (1) Split tunneling prevention policy, (2) VPN client configuration showing split tunneling disabled, (3) Network configuration evidence that all traffic routes through VPN when connected.",
    "SC.L2-3.13.8": "Provide: (1) Encryption-in-transit policy, (2) TLS 1.2+ configuration evidence for all CUI communications, (3) S3 bucket policies requiring aws:SecureTransport, (4) Site-to-Site VPN or Direct Connect encryption configuration, (5) ACM certificate inventory.",
    "SC.L2-3.13.9": "Provide: (1) Session termination policy with defined timeouts, (2) Application session timeout configurations, (3) Load balancer idle timeout settings, (4) SSH and RDP timeout configurations.",
    "SC.L2-3.13.10": "Provide: (1) Cryptographic key management policy, (2) KMS key inventory with rotation configuration, (3) Key access policies showing restricted management, (4) Key lifecycle documentation (creation, rotation, destruction), (5) CloudTrail logs for KMS key usage.",
    "SC.L2-3.13.11": "Provide: (1) FIPS cryptography policy, (2) FIPS endpoint configuration for AWS API calls, (3) KMS FIPS 140-2 validation documentation, (4) On-premises FIPS validated module certificates, (5) Cryptographic module inventory.",
    "SC.L2-3.13.12": "Provide: (1) Collaborative computing device policy, (2) Inventory of devices with remote activation capability, (3) Configuration showing remote activation is disabled, (4) Evidence of visible indicators when devices are active.",
    "SC.L2-3.13.13": "Provide: (1) Mobile code policy defining allowed technologies, (2) Browser and application configurations restricting mobile code, (3) Code signing requirements for approved mobile code.",
    "SC.L2-3.13.14": "Provide: (1) VoIP security policy, (2) VoIP encryption configuration, (3) Network segmentation for VoIP traffic, (4) Approved VoIP platform documentation.",
    "SC.L2-3.13.15": "Provide: (1) Session authenticity protection policy, (2) TLS certificate validation configuration, (3) Mutual TLS configuration for service-to-service communication if applicable, (4) DNSSEC configuration if applicable.",
    "SC.L2-3.13.16": "Provide: (1) Encryption-at-rest policy, (2) AWS Config rules for encryption (ENCRYPTED_VOLUMES, RDS_STORAGE_ENCRYPTED, S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED), (3) KMS key configurations for storage services, (4) On-premises full-disk encryption evidence (BitLocker, LUKS), (5) Database encryption configuration.",

    # SI — System and Information Integrity
    "SI.L2-3.14.1": "Provide: (1) Flaw remediation policy with defined timelines, (2) Systems Manager Patch Manager compliance reports, (3) Inspector vulnerability findings and remediation tracking, (4) AWS Config misconfiguration detection results, (5) Patch management metrics (time to patch by severity).",
    "SI.L2-3.14.2": "Provide: (1) Malware protection policy, (2) Antivirus/anti-malware deployment evidence on all CUI endpoints and servers, (3) GuardDuty Malware Protection configuration, (4) Malware detection and response records.",
    "SI.L2-3.14.3": "Provide: (1) Security alert monitoring policy, (2) Subscribed alert sources (CISA, US-CERT, AWS Security Bulletins, vendor advisories), (3) Alert review and response records, (4) Evidence of actions taken in response to advisories.",
    "SI.L2-3.14.4": "Provide: (1) Malware protection update policy, (2) Automatic update configuration evidence, (3) Update deployment logs showing timeliness, (4) Signature currency reports.",
    "SI.L2-3.14.5": "Provide: (1) Malware scanning policy (periodic and real-time), (2) Full-scan schedule configuration, (3) Real-time scanning configuration for downloads and external files, (4) Scan result reports.",
    "SI.L2-3.14.6": "Provide: (1) System monitoring policy, (2) GuardDuty configuration and finding examples, (3) VPC Flow Log monitoring configuration, (4) CloudTrail analysis for attack indicators, (5) SIEM or Security Hub alerting configuration for anomalous patterns, (6) Inbound and outbound traffic monitoring evidence.",
    "SI.L2-3.14.7": "Provide: (1) Unauthorized use detection policy, (2) Baseline behavior documentation, (3) Anomaly detection configuration (GuardDuty, CloudWatch anomaly detection), (4) Alert records for unauthorized use attempts, (5) Investigation records for detected anomalies.",
}


# =========================================================================
# Helper functions
# =========================================================================

def get_cmmc_custom_questions(practice_id: str) -> Optional[List[Dict[str, str]]]:
    """Get custom implementation questions for a CMMC practice.

    Args:
        practice_id: CMMC practice ID (e.g., 'AC.L2-3.1.1')

    Returns:
        List of question dicts if custom questions exist, None otherwise
    """
    return CMMC_CUSTOM_QUESTIONS.get(practice_id.upper())


def has_cmmc_custom_questions(practice_id: str) -> bool:
    """Check if custom implementation questions exist for a CMMC practice."""
    return practice_id.upper() in CMMC_CUSTOM_QUESTIONS


def get_cmmc_evidence_question(practice_id: str) -> Optional[str]:
    """Get custom evidence question for a CMMC practice.

    Args:
        practice_id: CMMC practice ID (e.g., 'AC.L2-3.1.1')

    Returns:
        Evidence question string if exists, None otherwise
    """
    return CMMC_EVIDENCE_QUESTIONS.get(practice_id.upper())


def has_cmmc_evidence_question(practice_id: str) -> bool:
    """Check if a custom evidence question exists for a CMMC practice."""
    return practice_id.upper() in CMMC_EVIDENCE_QUESTIONS
