"""Custom implementation questions for NIST CSF 2.0 subcategories.

These questions are designed to guide SAS advisors through specific, actionable
conversations with customer teams. Each question references concrete AWS services,
processes, and tools relevant to the subcategory outcome.

Only IMPLEMENTATION questions are custom here. Evidence, second-line, and
audit-readiness questions are generated by the standard generator.
"""

from typing import List, Dict, Optional

# CSF subcategory-specific implementation questions
# Each subcategory maps to a list of dicts with 'question' key
CSF_CUSTOM_QUESTIONS: Dict[str, List[Dict[str, str]]] = {

    # =========================================================================
    # GV — GOVERN
    # =========================================================================

    # GV.OC — Organizational Context
    "GV.OC-01": [
        {
            "question": "How does your organization document the relationship between its mission/business objectives and cybersecurity risk management? For example, is there a documented cybersecurity strategy that maps security investments to business priorities?"
        },
        {
            "question": "Have you defined which AWS workloads and data are mission-critical vs. supporting? How does this classification influence your security architecture decisions (e.g., multi-AZ, multi-Region, dedicated tenancy)?"
        },
    ],
    "GV.OC-02": [
        {
            "question": "Who are the key internal stakeholders (board, executives, IT, legal, compliance) and external stakeholders (regulators, customers, partners) whose cybersecurity expectations you must meet? How are their requirements documented and tracked?"
        },
        {
            "question": "How do you communicate cybersecurity risk posture to stakeholders? Do you use tools like AWS Security Hub dashboards, AWS Audit Manager reports, or custom reporting to keep stakeholders informed?"
        },
    ],
    "GV.OC-03": [
        {
            "question": "What legal, regulatory, and contractual cybersecurity requirements apply to your organization (e.g., PCI DSS, HIPAA, GDPR, SOC 2, FedRAMP)? How do you maintain a current inventory of these obligations?"
        },
        {
            "question": "How do you map these regulatory requirements to your AWS environment? Are you using AWS Audit Manager with pre-built framework assessments, AWS Artifact for compliance reports, or a GRC tool integrated with AWS?"
        },
    ],
    "GV.OC-04": [
        {
            "question": "Have you identified the critical services and capabilities that external stakeholders (customers, partners, regulators) depend on? How are SLAs and availability requirements documented for these services?"
        },
        {
            "question": "For customer-facing AWS workloads, how do you communicate security posture and incident status? Do you use AWS Health Dashboard, status pages, or contractual notification procedures?"
        },
    ],
    "GV.OC-05": [
        {
            "question": "What external services, suppliers, and dependencies does your organization rely on for critical operations (e.g., SaaS providers, managed services, AWS services)? How is this dependency inventory maintained?"
        },
        {
            "question": "How do you monitor the health and security posture of critical dependencies? For AWS services, are you using AWS Health, Service Health Dashboard, and Trusted Advisor to track dependency status?"
        },
    ],

    # GV.RM — Risk Management Strategy
    "GV.RM-01": [
        {
            "question": "Does your organization have documented cybersecurity risk management objectives that are agreed upon by senior leadership? How do these objectives align with enterprise risk management (ERM)?"
        },
        {
            "question": "How are cybersecurity risk management objectives translated into AWS-specific security requirements? For example, do you have documented standards for encryption, access control, and logging in AWS?"
        },
    ],
    "GV.RM-02": [
        {
            "question": "Has your organization defined and documented risk appetite and risk tolerance statements for cybersecurity? For example, what level of residual risk is acceptable for different data classifications?"
        },
        {
            "question": "How do risk tolerance statements influence AWS architecture decisions? For instance, does your risk appetite drive choices about encryption standards (KMS vs. CloudHSM), network isolation (VPC design), or data residency requirements?"
        },
    ],
    "GV.RM-03": [
        {
            "question": "How is cybersecurity risk integrated into your enterprise risk management (ERM) process? Does the CISO or security team report to the same risk governance body as financial, operational, and strategic risk?"
        },
        {
            "question": "Do you use AWS-native tools to feed cybersecurity risk data into ERM? For example, Security Hub findings aggregated into risk dashboards, or AWS Config compliance data feeding GRC platforms?"
        },
    ],
    "GV.RM-04": [
        {
            "question": "Does your organization have a documented risk response strategy that defines when to accept, mitigate, transfer, or avoid cybersecurity risks? How is this communicated to teams making AWS architecture decisions?"
        },
        {
            "question": "How do teams decide between risk response options in AWS? For example, when a Security Hub finding is identified, is there a documented process for deciding whether to remediate, accept with justification, or implement compensating controls?"
        },
    ],
    "GV.RM-05": [
        {
            "question": "What communication channels exist for reporting cybersecurity risks across the organization, including risks from suppliers and third parties? Is there a defined escalation path from technical teams to leadership?"
        },
        {
            "question": "How do AWS security findings flow to the right stakeholders? For example, do GuardDuty high-severity findings trigger SNS notifications to security teams, while Security Hub summaries go to management via scheduled reports?"
        },
    ],
    "GV.RM-06": [
        {
            "question": "Does your organization use a standardized risk scoring methodology (e.g., CVSS, FAIR, custom matrix) for cybersecurity risks? How are risks categorized and prioritized consistently across teams?"
        },
        {
            "question": "How do you prioritize remediation of AWS security findings? Do you use Security Hub severity scores, Inspector risk scores, or a custom prioritization model that factors in business context and asset criticality?"
        },
    ],
    "GV.RM-07": [
        {
            "question": "Does your organization consider strategic opportunities (positive risks) in cybersecurity discussions? For example, how security investments might enable new business capabilities, faster time-to-market, or competitive advantage?"
        },
    ],

    # GV.RR — Roles, Responsibilities, and Authorities
    "GV.RR-01": [
        {
            "question": "Who in your organization has executive accountability for cybersecurity risk (e.g., CISO, CTO, CRO)? How does leadership foster a risk-aware culture — through regular communications, metrics reviews, or incentive alignment?"
        },
        {
            "question": "Does your leadership team regularly review AWS security posture? For example, do they receive periodic briefings on Security Hub scores, compliance status from AWS Audit Manager, or cost of security operations?"
        },
    ],
    "GV.RR-02": [
        {
            "question": "Are cybersecurity roles and responsibilities clearly documented in a RACI matrix or similar artifact? Do teams understand who is responsible for AWS account security, workload security, data protection, and incident response?"
        },
        {
            "question": "How do you enforce the AWS shared responsibility model within your organization? Is it documented which teams own IAM policy management, network security, encryption key management, and patch management for EC2/containers?"
        },
    ],
    "GV.RR-03": [
        {
            "question": "How does your organization ensure adequate budget, staffing, and tooling for cybersecurity? Is there a process for requesting additional resources when new AWS workloads or compliance requirements are introduced?"
        },
        {
            "question": "Are you leveraging AWS-native security tools to optimize resource allocation? For example, using Security Hub for centralized findings instead of multiple point solutions, or AWS Config for automated compliance instead of manual reviews?"
        },
    ],
    "GV.RR-04": [
        {
            "question": "How is cybersecurity integrated into HR practices? Do job descriptions include security responsibilities? Is security awareness part of onboarding, performance reviews, and offboarding procedures?"
        },
        {
            "question": "When employees leave or change roles, how quickly are their AWS IAM credentials, SSO access, and console permissions revoked or modified? Is this process automated through identity provider integration (e.g., AWS IAM Identity Center with Okta, Azure AD)?"
        },
    ],

    # GV.PO — Policy
    "GV.PO-01": [
        {
            "question": "Does your organization have a documented cybersecurity policy that is based on your organizational context, risk strategy, and priorities? How is this policy communicated to all relevant personnel and enforced?"
        },
        {
            "question": "Does your cybersecurity policy include AWS-specific standards — for example, mandatory encryption at rest (KMS), required logging (CloudTrail in all regions), network segmentation (VPC design standards), or IAM policy requirements (no inline policies, MFA required)?"
        },
    ],
    "GV.PO-02": [
        {
            "question": "How often is your cybersecurity policy reviewed and updated? Is there a defined review cycle (e.g., annually) and a trigger-based review process for significant changes in threats, technology, or business requirements?"
        },
        {
            "question": "When AWS introduces new services or security features (e.g., new encryption options, new compliance certifications), how does your policy review process incorporate these changes? Who is responsible for evaluating and updating policies?"
        },
    ],

    # GV.SC — Cybersecurity Supply Chain Risk Management
    "GV.SC-01": [
        {
            "question": "Does your organization have a documented cybersecurity supply chain risk management (C-SCRM) program with strategy, objectives, and policies? Has it been agreed upon by organizational stakeholders?"
        },
        {
            "question": "Does your C-SCRM program address AWS Marketplace purchases, third-party AMIs, container images from public registries, and open-source dependencies used in your AWS workloads?"
        },
    ],
    "GV.SC-02": [
        {
            "question": "Are cybersecurity roles and responsibilities clearly defined for your suppliers, customers, and partners? For example, do contracts specify who is responsible for patching, monitoring, incident notification, and data protection?"
        },
    ],
    "GV.SC-03": [
        {
            "question": "How is supply chain risk management integrated into your overall cybersecurity and enterprise risk management processes? Do you assess supplier risks using the same methodology as internal risks?"
        },
    ],
    "GV.SC-04": [
        {
            "question": "Do you maintain an inventory of suppliers prioritized by criticality? How do you determine which suppliers are critical — based on data access, service dependency, or business impact?"
        },
        {
            "question": "For AWS-related suppliers (SaaS tools with AWS integrations, managed service providers, consulting partners), how do you assess and track their security posture? Do you require SOC 2 reports, penetration test results, or security questionnaire responses?"
        },
    ],
    "GV.SC-05": [
        {
            "question": "Do your contracts and agreements with suppliers include specific cybersecurity requirements (e.g., encryption standards, incident notification timelines, data handling requirements, right to audit)?"
        },
    ],
    "GV.SC-06": [
        {
            "question": "What due diligence do you perform before onboarding new suppliers or third parties? Do you conduct security assessments, review compliance certifications, or require evidence of security controls before granting access to your AWS environment?"
        },
    ],
    "GV.SC-07": [
        {
            "question": "How do you continuously monitor supplier risks throughout the relationship? Do you conduct periodic reassessments, review updated compliance reports, or use automated tools to monitor supplier security posture?"
        },
    ],
    "GV.SC-08": [
        {
            "question": "Are relevant suppliers and third parties included in your incident response planning and exercises? Do they know their roles during a security incident affecting your AWS environment?"
        },
    ],
    "GV.SC-09": [
        {
            "question": "How do you monitor supply chain security practices throughout the technology product and service lifecycle — from acquisition through deployment, operation, and decommissioning?"
        },
    ],
    "GV.SC-10": [
        {
            "question": "Do your supply chain risk management plans address what happens when a supplier relationship ends? How do you ensure data return/destruction, access revocation, and transition security when offboarding a supplier with access to your AWS environment?"
        },
    ],

    # =========================================================================
    # ID — IDENTIFY
    # =========================================================================

    # ID.AM — Asset Management
    "ID.AM-01": [
        {
            "question": "How do you maintain an inventory of hardware assets (servers, endpoints, network devices, IoT)? For AWS, are you using AWS Systems Manager Inventory, AWS Config resource tracking, or a CMDB integrated with AWS?"
        },
        {
            "question": "How do you discover and track EC2 instances, on-premises servers connected via Direct Connect, and edge devices? Are unmanaged or shadow IT assets detected through network scanning or AWS Config rules?"
        },
    ],
    "ID.AM-02": [
        {
            "question": "How do you maintain inventories of software, services, and systems? For AWS, are you tracking deployed services using AWS Config, AWS CloudFormation stack inventories, or AWS Service Catalog?"
        },
        {
            "question": "How do you track software installed on EC2 instances and containers? Are you using AWS Systems Manager Inventory for OS-level software, Amazon Inspector for package inventories, or ECR image scanning for container images?"
        },
    ],
    "ID.AM-03": [
        {
            "question": "Do you maintain network architecture diagrams showing authorized communication paths and data flows? For AWS, does this include VPC architectures, peering connections, Transit Gateway topologies, and internet-facing endpoints?"
        },
        {
            "question": "How do you detect unauthorized network flows? Are you using VPC Flow Logs analyzed with CloudWatch Logs Insights or Athena, AWS Network Firewall logs, or third-party network monitoring tools?"
        },
    ],
    "ID.AM-04": [
        {
            "question": "Do you maintain an inventory of services provided by external suppliers, including SaaS applications, managed services, and cloud service providers? How is this inventory kept current?"
        },
        {
            "question": "For AWS Marketplace subscriptions and third-party integrations, how do you track what external services have access to your AWS environment? Do you use AWS Marketplace subscription management, IAM Access Analyzer for external access, or a vendor management tool?"
        },
    ],
    "ID.AM-05": [
        {
            "question": "How do you classify and prioritize assets based on criticality, data sensitivity, and business impact? Do you use a formal data classification scheme (e.g., public, internal, confidential, restricted)?"
        },
        {
            "question": "In AWS, how do you tag resources to reflect classification and criticality? Are you using AWS resource tagging policies enforced through AWS Organizations SCPs or AWS Config rules like REQUIRED_TAGS?"
        },
    ],
    "ID.AM-07": [
        {
            "question": "How do you maintain inventories of data and associated metadata (data owner, classification, retention requirements, location)? For AWS, are you using Amazon Macie for S3 data discovery, AWS Glue Data Catalog, or a data governance platform?"
        },
        {
            "question": "How do you track where sensitive data resides across AWS services (S3, RDS, DynamoDB, Redshift, EBS)? Is Amazon Macie enabled for automated sensitive data discovery in S3 buckets?"
        },
    ],
    "ID.AM-08": [
        {
            "question": "How do you manage the lifecycle of systems, hardware, software, services, and data — from provisioning through operation to decommissioning? Are there documented procedures for secure disposal of AWS resources and data?"
        },
        {
            "question": "How do you ensure decommissioned AWS resources are properly cleaned up? Do you use AWS Config rules to detect unused resources, or automated cleanup processes for terminated instances, orphaned EBS volumes, and expired snapshots?"
        },
    ],

    # ID.RA — Risk Assessment
    "ID.RA-01": [
        {
            "question": "How do you identify and validate vulnerabilities in your assets? Are you using Amazon Inspector for EC2 and container vulnerability scanning, AWS Config for misconfiguration detection, or third-party vulnerability scanners?"
        },
        {
            "question": "How frequently are vulnerability scans performed? Is Amazon Inspector configured for continuous scanning, or do you run periodic scans? How are findings tracked and remediated — through Security Hub, Jira, or another ticketing system?"
        },
    ],
    "ID.RA-02": [
        {
            "question": "What cyber threat intelligence (CTI) sources does your organization consume? Do you subscribe to industry ISACs, government feeds (CISA), commercial threat intel, or AWS-native threat intelligence through GuardDuty?"
        },
        {
            "question": "How is threat intelligence operationalized in your AWS environment? For example, do GuardDuty threat lists include custom indicators, or do you feed external threat intel into WAF IP sets or Network Firewall rules?"
        },
    ],
    "ID.RA-03": [
        {
            "question": "How do you identify and document internal and external threats to your organization? Do you maintain a threat model or threat register that is regularly updated based on threat intelligence and incident history?"
        },
        {
            "question": "Have you performed threat modeling for your AWS workloads? Do you use frameworks like STRIDE or MITRE ATT&CK for Cloud to identify threats specific to your AWS architecture?"
        },
    ],
    "ID.RA-04": [
        {
            "question": "How do you assess the potential impact and likelihood of threats exploiting vulnerabilities? Do you use a formal risk assessment methodology (e.g., NIST SP 800-30, FAIR, qualitative risk matrices)?"
        },
        {
            "question": "For AWS-specific risks, how do you factor in the blast radius of a compromise? For example, do you assess the impact of a compromised IAM role, exposed S3 bucket, or breached VPC in terms of data exposure and business disruption?"
        },
    ],
    "ID.RA-05": [
        {
            "question": "How do you use threat, vulnerability, likelihood, and impact data to calculate inherent risk and prioritize risk responses? Is there a documented risk register that tracks these elements?"
        },
        {
            "question": "How do you prioritize remediation across AWS findings from multiple sources (Inspector, GuardDuty, Security Hub, Config)? Do you use Security Hub's consolidated severity scores, or a custom prioritization model?"
        },
    ],
    "ID.RA-06": [
        {
            "question": "How are risk responses (accept, mitigate, transfer, avoid) chosen, documented, and tracked? Is there a formal risk treatment plan with owners, timelines, and status tracking?"
        },
        {
            "question": "For AWS security findings, how do you document risk acceptance decisions? Do you use Security Hub workflow status (SUPPRESSED with justification), a GRC tool, or a risk register?"
        },
    ],
    "ID.RA-07": [
        {
            "question": "How do you manage changes and exceptions to security requirements? Is there a formal change management and exception process that includes risk assessment before approval?"
        },
        {
            "question": "For AWS environment changes, how do you assess security risk before deployment? Do you use AWS CloudFormation change sets, AWS Config conformance packs for drift detection, or pre-deployment security reviews?"
        },
    ],
    "ID.RA-08": [
        {
            "question": "Do you have a vulnerability disclosure program (VDP) or process for receiving, analyzing, and responding to vulnerability reports from external researchers or partners?"
        },
    ],
    "ID.RA-09": [
        {
            "question": "How do you assess the authenticity and integrity of hardware and software before acquisition and deployment? For AWS, do you verify AMI sources, validate container image signatures, or use AWS Signer for code signing?"
        },
    ],
    "ID.RA-10": [
        {
            "question": "How do you assess critical suppliers before acquisition? Do you review their security certifications (SOC 2, ISO 27001), conduct security questionnaires, or require evidence of security controls before onboarding?"
        },
    ],

    # ID.IM — Improvement
    "ID.IM-01": [
        {
            "question": "How do you identify cybersecurity improvements from evaluations such as audits, assessments, and reviews? Is there a formal process for tracking improvement actions to closure?"
        },
        {
            "question": "Do you use AWS Audit Manager assessment results, Security Hub findings trends, or AWS Well-Architected Reviews to identify improvement opportunities? How are findings translated into action items?"
        },
    ],
    "ID.IM-02": [
        {
            "question": "How do you identify improvements from security tests and exercises (penetration tests, red team exercises, tabletop exercises)? Are these conducted regularly and do they include your AWS environment?"
        },
        {
            "question": "Do you conduct penetration testing against your AWS workloads following AWS penetration testing policy? How are findings from these tests tracked and remediated?"
        },
    ],
    "ID.IM-03": [
        {
            "question": "How do you identify improvements from day-to-day operational processes? For example, do post-incident reviews, operational metrics, or near-miss analyses feed into your improvement program?"
        },
    ],
    "ID.IM-04": [
        {
            "question": "Do you have documented incident response plans that are regularly maintained and improved? Do these plans cover AWS-specific scenarios (compromised credentials, data exposure in S3, unauthorized resource creation)?"
        },
        {
            "question": "How often are incident response plans tested through tabletop exercises or simulations? Do exercises include AWS-specific scenarios and involve relevant AWS tools (GuardDuty, Detective, CloudTrail)?"
        },
    ],

    # =========================================================================
    # PR — PROTECT
    # =========================================================================

    # PR.AA — Identity Management, Authentication, and Access Control
    "PR.AA-01": [
        {
            "question": "How do you manage identities and credentials for users, services, and hardware? Are you using AWS IAM Identity Center (SSO) integrated with a corporate identity provider (Okta, Azure AD, Ping) for centralized identity management?"
        },
        {
            "question": "How do you manage service accounts and machine identities in AWS? Are you using IAM roles for EC2/ECS/Lambda instead of long-lived access keys? How are API keys rotated — manually or through AWS Secrets Manager automatic rotation?"
        },
    ],
    "PR.AA-02": [
        {
            "question": "How do you verify user identities before issuing credentials (identity proofing)? For privileged AWS access, is there an enhanced verification process beyond standard onboarding?"
        },
        {
            "question": "How are credentials bound to verified identities? For AWS, do you enforce that IAM users/roles map to verified individuals through your identity provider, with no shared or generic accounts?"
        },
    ],
    "PR.AA-03": [
        {
            "question": "What authentication mechanisms are in place for users, services, and hardware? Is MFA enforced for all AWS console access and CLI access? What MFA types are used (hardware tokens, virtual MFA, FIDO2)?"
        },
        {
            "question": "How do you authenticate service-to-service communication in AWS? Are you using IAM roles with STS temporary credentials, VPC endpoints for private API access, or mutual TLS for service mesh communication?"
        },
    ],
    "PR.AA-04": [
        {
            "question": "How are identity assertions (tokens, certificates, SAML assertions) protected, conveyed, and verified? For AWS, how do you secure SAML/OIDC federation tokens between your identity provider and AWS IAM Identity Center?"
        },
    ],
    "PR.AA-05": [
        {
            "question": "How do you implement least privilege and separation of duties in AWS? Are IAM policies scoped to specific resources and actions? Do you use AWS Organizations SCPs to set permission boundaries across accounts?"
        },
        {
            "question": "How do you review and right-size access permissions? Are you using IAM Access Analyzer to identify unused permissions, AWS CloudTrail to analyze actual API usage, or IAM policy simulator to test policies before deployment?"
        },
    ],
    "PR.AA-06": [
        {
            "question": "How is physical access to assets managed and monitored? For AWS, do you rely on AWS data center physical security (documented in SOC reports via AWS Artifact), and what physical controls protect on-premises infrastructure that connects to AWS?"
        },
    ],

    # PR.AT — Awareness and Training
    "PR.AT-01": [
        {
            "question": "What cybersecurity awareness training do all personnel receive? Does it cover AWS-specific topics like phishing for console credentials, secure use of access keys, recognizing suspicious CloudTrail activity, and data handling in S3?"
        },
        {
            "question": "How do you measure training effectiveness? Do you track completion rates, conduct phishing simulations, or test knowledge retention? How often is training refreshed?"
        },
    ],
    "PR.AT-02": [
        {
            "question": "What specialized security training do personnel in roles like cloud architects, DevOps engineers, security analysts, and incident responders receive? Does it include AWS-specific security certifications or hands-on labs?"
        },
        {
            "question": "For teams managing AWS infrastructure, do they receive training on IAM best practices, secure VPC design, encryption with KMS, CloudTrail analysis, and incident response using GuardDuty and Detective?"
        },
    ],

    # PR.DS — Data Security
    "PR.DS-01": [
        {
            "question": "How do you protect data at rest? In AWS, is encryption enabled for all storage services — S3 (SSE-S3, SSE-KMS, SSE-C), EBS volumes, RDS instances, DynamoDB tables, and Redshift clusters? What key management approach do you use (AWS managed keys vs. customer managed KMS keys)?"
        },
        {
            "question": "Are AWS Config rules enabled to detect unencrypted resources (e.g., S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED, ENCRYPTED_VOLUMES, RDS_STORAGE_ENCRYPTED)? How are violations remediated — manually or through automated remediation?"
        },
    ],
    "PR.DS-02": [
        {
            "question": "How do you protect data in transit? Is TLS 1.2+ enforced for all communications? In AWS, are you using ACM for certificate management, ALB/CloudFront with HTTPS-only policies, and S3 bucket policies requiring ssl-only (aws:SecureTransport)?"
        },
        {
            "question": "For internal service communication, how is data in transit protected? Are you using VPC endpoints for AWS service access, PrivateLink for cross-account communication, or service mesh with mTLS for microservices?"
        },
    ],
    "PR.DS-10": [
        {
            "question": "How do you protect data in use (data being actively processed in memory)? Are you using AWS Nitro Enclaves for sensitive data processing, or considering Nitro-based instances that provide hardware-level memory isolation?"
        },
    ],
    "PR.DS-11": [
        {
            "question": "How are backups created, protected, and tested? In AWS, are you using AWS Backup for centralized backup management across services (EBS, RDS, DynamoDB, EFS, S3)? Are backup policies defined with appropriate retention periods and cross-Region replication?"
        },
        {
            "question": "How often do you test backup restoration? Are backup vaults protected with AWS Backup Vault Lock to prevent deletion? Are backups encrypted with customer-managed KMS keys?"
        },
    ],

    # PR.PS — Platform Security
    "PR.PS-01": [
        {
            "question": "How do you establish and enforce configuration management baselines? In AWS, are you using AWS Config conformance packs, Security Hub standards (CIS AWS Foundations, AWS Foundational Security Best Practices), or custom Config rules to enforce configuration standards?"
        },
        {
            "question": "How do you detect and remediate configuration drift? Are AWS Config rules set to auto-remediate common misconfigurations (e.g., public S3 buckets, unrestricted security groups, unencrypted resources)?"
        },
    ],
    "PR.PS-02": [
        {
            "question": "How do you manage software maintenance, patching, and end-of-life? For EC2 instances, are you using AWS Systems Manager Patch Manager for automated patching? For containers, how do you update base images and scan for vulnerabilities with Amazon ECR image scanning or Inspector?"
        },
        {
            "question": "How do you track software end-of-life and ensure timely upgrades? Are you monitoring for EOL operating systems and runtimes using Inspector or Systems Manager inventory?"
        },
    ],
    "PR.PS-03": [
        {
            "question": "How do you manage hardware lifecycle in AWS? For on-premises hardware connected to AWS (Direct Connect routers, hybrid infrastructure), how do you track maintenance schedules and end-of-life replacement?"
        },
    ],
    "PR.PS-04": [
        {
            "question": "How do you generate and manage log records for continuous monitoring? Is AWS CloudTrail enabled in all regions with management and data events? Are VPC Flow Logs, S3 access logs, and application logs centralized in CloudWatch Logs or a SIEM?"
        },
        {
            "question": "How long are logs retained, and where are they stored? Are CloudTrail logs stored in a dedicated logging account S3 bucket with object lock? Are CloudWatch Log group retention periods configured per your compliance requirements?"
        },
    ],
    "PR.PS-05": [
        {
            "question": "How do you prevent installation and execution of unauthorized software? In AWS, are you using Systems Manager Application Manager, EC2 Image Builder for hardened AMIs, or AWS Organizations SCPs to restrict which services and regions can be used?"
        },
    ],
    "PR.PS-06": [
        {
            "question": "How are secure software development practices integrated into your SDLC? Do you use CodeGuru for code reviews, CodePipeline with security scanning stages, SAST/DAST tools, and dependency vulnerability scanning in your CI/CD pipeline?"
        },
        {
            "question": "How do you manage open-source dependencies and third-party libraries? Are you using Amazon CodeGuru Security, Snyk, or similar tools integrated into your build pipeline to detect vulnerable dependencies?"
        },
    ],

    # PR.IR — Technology Infrastructure Resilience
    "PR.IR-01": [
        {
            "question": "How do you protect networks from unauthorized access? In AWS, are you using VPC security groups with least-privilege rules, Network ACLs, AWS Network Firewall, and WAF for web application protection? How are security group rules reviewed and cleaned up?"
        },
        {
            "question": "How do you segment your AWS network? Do you use separate VPCs or accounts for different environments (dev/staging/prod) and workload types? Are you using AWS Transit Gateway with route table segmentation or AWS Network Firewall for inter-VPC traffic inspection?"
        },
    ],
    "PR.IR-02": [
        {
            "question": "How do you protect technology assets from environmental threats (power failures, cooling failures, natural disasters)? For AWS workloads, are you leveraging multi-AZ deployments and multi-Region architectures for critical systems?"
        },
    ],
    "PR.IR-03": [
        {
            "question": "What resilience mechanisms are in place for normal and adverse situations? Are you using Auto Scaling groups, multi-AZ RDS deployments, S3 cross-Region replication, and Route 53 health checks with failover routing?"
        },
        {
            "question": "Have you tested your resilience mechanisms? Do you conduct chaos engineering exercises (e.g., AWS Fault Injection Service) or disaster recovery drills to validate failover and recovery procedures?"
        },
    ],
    "PR.IR-04": [
        {
            "question": "How do you ensure adequate resource capacity for availability? Are you using AWS Auto Scaling, reserved capacity, or on-demand scaling policies? Do you monitor capacity with CloudWatch alarms and Trusted Advisor service limit checks?"
        },
    ],

    # =========================================================================
    # DE — DETECT
    # =========================================================================

    # DE.CM — Continuous Monitoring
    "DE.CM-01": [
        {
            "question": "How do you monitor networks for potentially adverse events? Are you using VPC Flow Logs analyzed with CloudWatch Logs Insights or Athena, AWS Network Firewall alert logs, GuardDuty network-based findings, or a third-party SIEM/NDR solution?"
        },
        {
            "question": "What network-based detection rules or anomaly detection are in place? Does GuardDuty monitor for port scanning, DNS exfiltration, cryptocurrency mining, and unauthorized API calls from unusual IP ranges?"
        },
    ],
    "DE.CM-02": [
        {
            "question": "How do you monitor the physical environment for adverse events? For AWS, do you rely on AWS data center physical monitoring (documented in SOC reports)? For on-premises infrastructure, what environmental monitoring is in place (temperature, humidity, water detection, power)?"
        },
    ],
    "DE.CM-03": [
        {
            "question": "How do you monitor personnel activity and technology usage for adverse events? Are you using CloudTrail for API activity monitoring, GuardDuty for anomalous user behavior detection, and IAM Access Analyzer for access pattern analysis?"
        },
        {
            "question": "Do you monitor for insider threat indicators in AWS? For example, unusual data downloads from S3, access to resources outside normal working hours, or privilege escalation attempts detected by GuardDuty?"
        },
    ],
    "DE.CM-06": [
        {
            "question": "How do you monitor external service provider activities? For third-party tools with AWS access, do you monitor their API calls via CloudTrail, restrict their permissions with IAM policies, and review their activity logs?"
        },
        {
            "question": "For AWS Marketplace products and SaaS integrations, how do you monitor their behavior in your environment? Are cross-account IAM roles scoped to minimum permissions with external ID conditions?"
        },
    ],
    "DE.CM-09": [
        {
            "question": "How do you monitor computing resources, runtime environments, and data for adverse events? Are you using Amazon Inspector for continuous vulnerability assessment, GuardDuty for runtime threat detection (EC2, ECS, EKS, Lambda), and CloudWatch for application-level anomaly detection?"
        },
        {
            "question": "For containerized workloads, is GuardDuty EKS Runtime Monitoring or ECS Runtime Monitoring enabled? For Lambda functions, is GuardDuty Lambda Protection active? How are runtime findings triaged and responded to?"
        },
    ],

    # DE.AE — Adverse Event Analysis
    "DE.AE-02": [
        {
            "question": "How do you analyze potentially adverse events to understand associated activities? Do you use Amazon Detective for investigation and visualization of security findings, CloudTrail Lake for historical query analysis, or a SIEM for event correlation?"
        },
        {
            "question": "When a GuardDuty finding is generated, what is the analysis workflow? Do analysts use Detective to visualize entity relationships, query CloudTrail for related API calls, and check VPC Flow Logs for network context?"
        },
    ],
    "DE.AE-03": [
        {
            "question": "How do you correlate information from multiple sources to detect security incidents? Are you aggregating findings from GuardDuty, Security Hub, Inspector, Macie, and CloudTrail into a centralized platform for correlation?"
        },
        {
            "question": "Is AWS Security Hub configured as your central aggregation point? Are findings from all AWS security services and third-party tools flowing into Security Hub for cross-source correlation and prioritization?"
        },
    ],
    "DE.AE-04": [
        {
            "question": "How do you estimate the impact and scope of adverse events? Do you have a classification system for incident severity that considers data sensitivity, number of affected resources, blast radius, and business impact?"
        },
        {
            "question": "When a security event is detected in AWS, how do you quickly determine scope? Do you use Amazon Detective to map affected resources, IAM Access Analyzer to assess permission exposure, or CloudTrail to trace the attacker's actions across accounts?"
        },
    ],
    "DE.AE-06": [
        {
            "question": "How is information on adverse events provided to authorized staff and tools? Are Security Hub findings, GuardDuty alerts, and CloudWatch alarms routed to the right teams via SNS, EventBridge, PagerDuty, or Slack integrations?"
        },
        {
            "question": "Do you have tiered notification routing based on severity? For example, critical GuardDuty findings trigger immediate pages to the security team, while medium findings create tickets for next-business-day review?"
        },
    ],
    "DE.AE-07": [
        {
            "question": "How do you integrate cyber threat intelligence into your analysis of adverse events? Does GuardDuty use custom threat lists? Do you enrich Security Hub findings with external threat intel before triage?"
        },
    ],
    "DE.AE-08": [
        {
            "question": "What criteria define when an adverse event is declared as a security incident? Do you have documented incident declaration criteria that map to GuardDuty severity levels, Security Hub finding types, or specific event patterns?"
        },
        {
            "question": "Who has the authority to declare a security incident, and how is the declaration communicated? Is there an automated escalation path from Security Hub critical findings to incident declaration?"
        },
    ],

    # =========================================================================
    # RS — RESPOND
    # =========================================================================

    # RS.MA — Incident Management
    "RS.MA-01": [
        {
            "question": "Do you have a documented incident response plan that is executed when an incident is declared? Does it include AWS-specific runbooks for common scenarios (compromised IAM credentials, exposed S3 data, unauthorized EC2 instances, ransomware)?"
        },
        {
            "question": "How do you coordinate incident response with relevant third parties (AWS Support, law enforcement, customers, regulators)? Do you have AWS Enterprise Support or Incident Detection and Response (IDR) for critical incidents?"
        },
    ],
    "RS.MA-02": [
        {
            "question": "How are incident reports triaged and validated? Do you use Security Hub workflow status to track triage, or a dedicated incident management platform (PagerDuty, ServiceNow, Jira) integrated with AWS findings?"
        },
    ],
    "RS.MA-03": [
        {
            "question": "How do you categorize and prioritize incidents? Do you use a severity classification system (e.g., SEV1-SEV4) that maps to GuardDuty severity levels and drives response timelines and escalation procedures?"
        },
    ],
    "RS.MA-04": [
        {
            "question": "What escalation procedures are in place for security incidents? Are there defined criteria for escalating to senior management, legal, communications, or AWS Support based on incident severity and scope?"
        },
    ],
    "RS.MA-05": [
        {
            "question": "What criteria determine when incident recovery should be initiated? How do you decide when containment is sufficient and restoration can begin — for example, after confirming the attacker's access has been revoked and affected resources are isolated?"
        },
    ],

    # RS.AN — Incident Analysis
    "RS.AN-03": [
        {
            "question": "How do you perform root cause analysis during and after incidents? Do you use Amazon Detective for entity-level investigation, CloudTrail Lake for historical API analysis, or forensic tools for memory/disk analysis of compromised EC2 instances?"
        },
        {
            "question": "For AWS incidents, can you reconstruct the attack timeline using CloudTrail events, VPC Flow Logs, and GuardDuty findings? Do you have the tools and skills to perform forensic analysis of EC2 instances (EBS snapshot analysis, memory capture)?"
        },
    ],
    "RS.AN-06": [
        {
            "question": "How do you ensure investigation actions are recorded with integrity preserved? Are CloudTrail logs stored in an immutable location (S3 with Object Lock)? Do you maintain a chain of custody for forensic evidence?"
        },
    ],
    "RS.AN-07": [
        {
            "question": "How do you collect and preserve incident data and metadata? Do you have automated evidence collection procedures — for example, scripts to snapshot EBS volumes, capture EC2 instance metadata, and export CloudTrail logs for affected time periods?"
        },
    ],
    "RS.AN-08": [
        {
            "question": "How do you estimate and validate an incident's magnitude (number of affected systems, data records exposed, business impact)? Do you use Amazon Detective's scope analysis, Macie for data exposure assessment, or manual investigation procedures?"
        },
    ],

    # RS.CO — Incident Response Reporting and Communication
    "RS.CO-02": [
        {
            "question": "How do you notify internal and external stakeholders of incidents? Do you have pre-defined communication templates, notification lists, and escalation procedures for different incident types and severities?"
        },
        {
            "question": "For incidents involving regulated data (PCI, HIPAA, GDPR), do you have documented notification timelines and procedures that meet regulatory requirements? How do you coordinate with AWS if the incident involves AWS infrastructure?"
        },
    ],
    "RS.CO-03": [
        {
            "question": "How do you share incident information with designated stakeholders? Do you use a war room, incident management platform, or status page? How do you control information sharing to prevent premature disclosure?"
        },
    ],

    # RS.MI — Incident Mitigation
    "RS.MI-01": [
        {
            "question": "How do you contain security incidents in AWS? Do you have runbooks for common containment actions — isolating EC2 instances (modifying security groups), revoking IAM credentials, blocking IP addresses with WAF/Network Firewall, or disabling compromised access keys?"
        },
        {
            "question": "Can you perform containment actions quickly? Are containment procedures automated through Lambda functions triggered by Security Hub custom actions, or do they require manual execution? What is your target containment time for critical incidents?"
        },
    ],
    "RS.MI-02": [
        {
            "question": "How do you eradicate threats after containment? For AWS incidents, do you have procedures for removing unauthorized resources, rotating all potentially compromised credentials, patching exploited vulnerabilities, and rebuilding affected systems from known-good images?"
        },
    ],

    # =========================================================================
    # RC — RECOVER
    # =========================================================================

    # RC.RP — Incident Recovery Plan Execution
    "RC.RP-01": [
        {
            "question": "Do you have a documented recovery plan that is part of your incident response process? Does it include AWS-specific recovery procedures — restoring from AWS Backup, redeploying infrastructure from CloudFormation/CDK, and failover to DR regions?"
        },
        {
            "question": "How do you initiate recovery? Is there a defined handoff from incident response (containment/eradication) to recovery? Who authorizes the start of recovery operations?"
        },
    ],
    "RC.RP-02": [
        {
            "question": "How do you select, scope, and prioritize recovery actions? Do you have a prioritized list of critical systems and services with defined Recovery Time Objectives (RTOs) and Recovery Point Objectives (RPOs) that guide recovery sequencing?"
        },
    ],
    "RC.RP-03": [
        {
            "question": "How do you verify the integrity of backups and restoration assets before using them? For AWS, do you validate that AWS Backup recovery points are not compromised, EBS snapshots are clean, and AMIs used for rebuilding are from trusted sources?"
        },
    ],
    "RC.RP-04": [
        {
            "question": "How do you establish post-incident operational norms? After recovery, do you conduct a security review to determine if additional controls are needed, update baselines, and adjust monitoring before returning to normal operations?"
        },
    ],
    "RC.RP-05": [
        {
            "question": "How do you verify the integrity of restored assets and confirm normal operating status? Do you run security scans (Inspector, Config compliance checks) on restored systems before returning them to production? How do you confirm services are operating normally?"
        },
    ],
    "RC.RP-06": [
        {
            "question": "What criteria determine the end of incident recovery? How do you formally close an incident — including completing documentation, conducting a post-incident review (lessons learned), and updating incident response plans based on findings?"
        },
    ],

    # RC.CO — Incident Recovery Communication
    "RC.CO-03": [
        {
            "question": "How do you communicate recovery activities and progress to internal and external stakeholders? Do you provide regular status updates during recovery, and a final recovery report when operations are restored?"
        },
    ],
    "RC.CO-04": [
        {
            "question": "How do you manage public communications about incident recovery? Do you have approved messaging templates, a designated spokesperson, and a process for coordinating public statements with legal and communications teams?"
        },
    ],
}


# =========================================================================
# CSF EVIDENCE QUESTIONS
# Each subcategory maps to a single evidence question string that guides
# the advisor toward specific, auditable evidence artifacts.
# =========================================================================
CSF_EVIDENCE_QUESTIONS: Dict[str, str] = {

    # GV.OC — Organizational Context
    "GV.OC-01": "Provide: (1) Documented cybersecurity strategy or charter that links security objectives to business mission, (2) Board or executive meeting minutes showing cybersecurity risk discussions, (3) Risk register entries that reference mission-critical systems. Where are these maintained and who owns them?",
    "GV.OC-02": "Provide: (1) Stakeholder register identifying internal and external parties with cybersecurity expectations, (2) Communication records showing how cybersecurity posture is reported to stakeholders (e.g., Security Hub dashboards, Audit Manager reports, board presentations), (3) Requirements traceability matrix mapping stakeholder needs to security controls.",
    "GV.OC-03": "Provide: (1) Inventory of applicable legal, regulatory, and contractual cybersecurity requirements (e.g., PCI DSS, HIPAA, GDPR, SOC 2), (2) AWS Audit Manager assessment reports for applicable frameworks, (3) AWS Artifact compliance reports downloaded for your account, (4) GRC tool records showing how obligations are tracked and updated.",
    "GV.OC-04": "Provide: (1) Service catalog or dependency map identifying critical services external stakeholders depend on, (2) SLA documentation with availability and security commitments, (3) Communication procedures for notifying stakeholders of security incidents affecting their services.",
    "GV.OC-05": "Provide: (1) Dependency inventory listing external services, suppliers, and AWS services critical to operations, (2) AWS Health Dashboard or Trusted Advisor reports showing dependency monitoring, (3) Business impact analysis documenting consequences of dependency failures.",

    # GV.RM — Risk Management Strategy
    "GV.RM-01": "Provide: (1) Documented cybersecurity risk management objectives approved by senior leadership, (2) Meeting minutes or sign-off records showing stakeholder agreement, (3) Mapping document showing how risk objectives align with enterprise risk management.",
    "GV.RM-02": "Provide: (1) Formal risk appetite and risk tolerance statements approved by leadership, (2) Evidence these statements are communicated to teams (e.g., policy documents, training materials), (3) Examples of how risk tolerance influenced AWS architecture decisions (e.g., encryption standards, network isolation choices).",
    "GV.RM-03": "Provide: (1) Enterprise risk management framework documentation showing cybersecurity integration, (2) Risk committee meeting minutes where cybersecurity risks are discussed alongside other enterprise risks, (3) Consolidated risk register that includes cybersecurity risks.",
    "GV.RM-04": "Provide: (1) Documented risk response strategy defining accept/mitigate/transfer/avoid criteria, (2) Examples of risk response decisions with documented rationale (e.g., Security Hub finding suppressed with justification, risk accepted in risk register), (3) Communication records showing strategy distribution to teams.",
    "GV.RM-05": "Provide: (1) Documented communication channels and escalation paths for cybersecurity risks, (2) Examples of risk communications (e.g., GuardDuty alert notifications via SNS, Security Hub summary reports to management), (3) Evidence of third-party/supplier risk communication procedures.",
    "GV.RM-06": "Provide: (1) Documented risk scoring methodology (e.g., CVSS, FAIR, custom matrix), (2) Risk register showing consistent application of the methodology, (3) Examples of how Security Hub severity scores or Inspector risk scores are mapped to your internal risk categories.",
    "GV.RM-07": "Provide: (1) Documentation showing positive risk (opportunity) discussions in cybersecurity risk reviews, (2) Examples of security investments that enabled business capabilities or competitive advantage.",

    # GV.RR — Roles, Responsibilities, and Authorities
    "GV.RR-01": "Provide: (1) Organizational chart showing executive accountability for cybersecurity (CISO, CTO, CRO reporting line), (2) Board or leadership meeting minutes showing cybersecurity risk reviews, (3) Evidence of risk-aware culture initiatives (communications, metrics dashboards, incentive alignment).",
    "GV.RR-02": "Provide: (1) RACI matrix or responsibility assignment document for cybersecurity functions, (2) AWS shared responsibility model documentation showing team ownership of IAM, network, encryption, patching, (3) Job descriptions or role definitions that include security responsibilities.",
    "GV.RR-03": "Provide: (1) Cybersecurity budget documentation and resource allocation records, (2) Staffing plans for security roles, (3) Tooling inventory showing security tools deployed (Security Hub, GuardDuty, Config, Inspector, etc.).",
    "GV.RR-04": "Provide: (1) HR policies that include cybersecurity responsibilities (onboarding, offboarding, role changes), (2) Evidence of security awareness in job descriptions and performance reviews, (3) IAM Identity Center or IdP logs showing timely access revocation when employees leave or change roles.",

    # GV.PO — Policy
    "GV.PO-01": "Provide: (1) Cybersecurity policy document with approval signatures and effective date, (2) Evidence of policy communication to personnel (email distribution, training acknowledgments, intranet posting), (3) AWS-specific standards referenced in the policy (encryption requirements, logging standards, IAM policy standards).",
    "GV.PO-02": "Provide: (1) Policy review records showing review dates, reviewers, and changes made, (2) Change log or version history of the cybersecurity policy, (3) Evidence of trigger-based reviews when significant changes occurred (new AWS services adopted, new regulations, major incidents).",

    # GV.SC — Supply Chain Risk Management
    "GV.SC-01": "Provide: (1) Documented C-SCRM program with strategy, objectives, and policies, (2) Stakeholder sign-off on the program, (3) Evidence the program addresses cloud-specific supply chain risks (AWS Marketplace, third-party AMIs, open-source dependencies).",
    "GV.SC-02": "Provide: (1) Contracts or agreements with suppliers that define cybersecurity roles and responsibilities, (2) Communication records showing coordination of security responsibilities with suppliers and partners.",
    "GV.SC-03": "Provide: (1) Risk management framework documentation showing supply chain risk integration, (2) Risk assessment records that include supplier/third-party risks alongside internal risks.",
    "GV.SC-04": "Provide: (1) Supplier inventory with criticality ratings and justification, (2) Criteria used to determine supplier criticality (data access level, service dependency, business impact), (3) For AWS-related suppliers — SOC 2 reports, security questionnaire responses, or compliance certifications on file.",
    "GV.SC-05": "Provide: (1) Contract templates or clauses that include cybersecurity requirements (encryption, incident notification, data handling, right to audit), (2) Examples of executed contracts with these provisions.",
    "GV.SC-06": "Provide: (1) Due diligence checklist or process documentation for new supplier onboarding, (2) Completed security assessments for recently onboarded suppliers, (3) Evidence of compliance certification review before granting AWS environment access.",
    "GV.SC-07": "Provide: (1) Supplier monitoring schedule and records of periodic reassessments, (2) Updated compliance reports or security questionnaire responses from active suppliers, (3) Risk register entries tracking ongoing supplier risks.",
    "GV.SC-08": "Provide: (1) Incident response plan sections that include supplier roles and responsibilities, (2) Evidence of supplier participation in incident response exercises or tabletop drills.",
    "GV.SC-09": "Provide: (1) Lifecycle management procedures for technology products and services, (2) Evidence of supply chain security monitoring throughout acquisition, deployment, operation, and decommissioning phases.",
    "GV.SC-10": "Provide: (1) Supplier offboarding procedures addressing data return/destruction and access revocation, (2) Evidence of executed offboarding for terminated supplier relationships (IAM role deletion records, access revocation logs).",

    # ID.AM — Asset Management
    "ID.AM-01": "Provide: (1) Hardware asset inventory report from AWS Systems Manager Inventory, AWS Config resource list, or CMDB, (2) Evidence of regular inventory reconciliation, (3) Process documentation for discovering and registering new hardware assets including EC2 instances.",
    "ID.AM-02": "Provide: (1) Software and service inventory from AWS Config, CloudFormation stack list, or Service Catalog, (2) Systems Manager Inventory reports showing installed software on EC2 instances, (3) Container image inventory from ECR with scan results from Inspector.",
    "ID.AM-03": "Provide: (1) Network architecture diagrams showing VPC topologies, peering connections, Transit Gateway, and internet-facing endpoints, (2) VPC Flow Log analysis reports showing authorized communication patterns, (3) Evidence diagrams are reviewed and updated when network changes occur.",
    "ID.AM-04": "Provide: (1) Supplier service inventory including SaaS applications and managed services, (2) AWS Marketplace subscription list, (3) IAM Access Analyzer findings showing external access granted to third-party services.",
    "ID.AM-05": "Provide: (1) Asset classification policy defining criticality levels and data sensitivity categories, (2) AWS resource tagging reports showing classification tags applied, (3) AWS Config rule results for REQUIRED_TAGS showing tagging compliance.",
    "ID.AM-07": "Provide: (1) Data inventory with classification, ownership, and retention metadata, (2) Amazon Macie sensitive data discovery reports for S3 buckets, (3) AWS Glue Data Catalog entries or data governance platform records showing data lineage.",
    "ID.AM-08": "Provide: (1) Lifecycle management procedures for systems, software, and data, (2) Evidence of secure decommissioning (terminated instance logs, deleted EBS volume records, S3 lifecycle policy configurations), (3) AWS Config rules detecting orphaned or unused resources.",

    # ID.RA — Risk Assessment
    "ID.RA-01": "Provide: (1) Amazon Inspector vulnerability scan reports showing identified vulnerabilities, (2) AWS Config non-compliant resource reports for misconfiguration detection, (3) Vulnerability tracking records showing remediation status and timelines.",
    "ID.RA-02": "Provide: (1) List of threat intelligence sources consumed (ISACs, CISA feeds, commercial CTI, GuardDuty threat lists), (2) Evidence of threat intel integration into security tools (GuardDuty custom threat lists, WAF IP sets), (3) Threat intelligence review meeting records.",
    "ID.RA-03": "Provide: (1) Threat register or threat model documentation, (2) Evidence of threat modeling for AWS workloads (STRIDE analysis, MITRE ATT&CK for Cloud mapping), (3) Records showing threat register is updated based on new intelligence and incidents.",
    "ID.RA-04": "Provide: (1) Risk assessment reports showing impact and likelihood ratings for identified threats, (2) Risk assessment methodology documentation (NIST SP 800-30, FAIR, or custom), (3) Examples of blast radius analysis for AWS-specific scenarios.",
    "ID.RA-05": "Provide: (1) Risk register with inherent risk scores calculated from threat, vulnerability, likelihood, and impact data, (2) Risk prioritization records showing how remediation is sequenced, (3) Security Hub findings with severity-based triage documentation.",
    "ID.RA-06": "Provide: (1) Risk treatment plan with owners, timelines, and status for each risk response, (2) Risk acceptance records with documented justification and approver signatures, (3) Security Hub workflow status records showing SUPPRESSED findings with rationale.",
    "ID.RA-07": "Provide: (1) Change management process documentation including security risk assessment steps, (2) Change request records showing security review before approval, (3) AWS Config drift detection reports or CloudFormation change set reviews.",
    "ID.RA-08": "Provide: (1) Vulnerability disclosure program documentation or policy, (2) Records of vulnerability reports received and response actions taken.",
    "ID.RA-09": "Provide: (1) Software/hardware integrity verification procedures, (2) Evidence of AMI source validation, container image signature verification (AWS Signer), or code signing practices.",
    "ID.RA-10": "Provide: (1) Pre-acquisition security assessment records for critical suppliers, (2) Compliance certification reviews (SOC 2, ISO 27001) conducted before supplier onboarding.",

    # ID.IM — Improvement
    "ID.IM-01": "Provide: (1) Audit or assessment findings with associated improvement action items, (2) AWS Audit Manager assessment results showing identified gaps, (3) Action item tracking records showing closure status and timelines.",
    "ID.IM-02": "Provide: (1) Penetration test reports for AWS workloads (following AWS pen test policy), (2) Red team or tabletop exercise after-action reports, (3) Remediation tracking records for findings from security tests.",
    "ID.IM-03": "Provide: (1) Post-incident review reports with improvement recommendations, (2) Operational metrics showing trends (e.g., mean time to detect, mean time to respond), (3) Process improvement records from day-to-day operations.",
    "ID.IM-04": "Provide: (1) Incident response plan document with version history showing updates, (2) Tabletop exercise or simulation records including AWS-specific scenarios, (3) After-action reports showing plan improvements made after exercises or real incidents.",

    # PR.AA — Identity Management, Authentication, and Access Control
    "PR.AA-01": "Provide: (1) IAM Identity Center (SSO) configuration showing identity provider integration, (2) IAM credential report showing user accounts, MFA status, and access key age, (3) Process documentation for identity lifecycle management (creation, modification, deactivation).",
    "PR.AA-02": "Provide: (1) Identity proofing procedures documentation, (2) Evidence of enhanced verification for privileged access, (3) Records showing credentials are bound to verified individuals (no shared or generic accounts in IAM).",
    "PR.AA-03": "Provide: (1) MFA enforcement evidence — IAM policy requiring MFA, SCP enforcing MFA, or Identity Center MFA configuration, (2) IAM credential report showing MFA enabled for all users, (3) Service authentication evidence — IAM roles used instead of long-lived access keys for EC2/ECS/Lambda.",
    "PR.AA-04": "Provide: (1) SAML/OIDC federation configuration between identity provider and AWS IAM Identity Center, (2) Token/assertion security configuration (signing, encryption, expiration settings), (3) Certificate management records for federation trust.",
    "PR.AA-05": "Provide: (1) IAM Access Analyzer findings report showing unused permissions identified, (2) SCP policies enforcing permission boundaries across accounts, (3) IAM policy review records showing least privilege validation, (4) Separation of duties documentation for critical functions.",
    "PR.AA-06": "Provide: (1) AWS Artifact SOC reports documenting AWS data center physical security, (2) For on-premises infrastructure — physical access logs, surveillance records, and access control system reports.",

    # PR.AT — Awareness and Training
    "PR.AT-01": "Provide: (1) Security awareness training curriculum including AWS-specific topics, (2) Training completion records showing percentage of personnel trained, (3) Phishing simulation results and trend data, (4) Training effectiveness metrics.",
    "PR.AT-02": "Provide: (1) Specialized training curriculum for cloud architects, DevOps, security analysts, (2) AWS certification records for relevant personnel, (3) Hands-on lab or exercise completion records for AWS security topics (IAM, VPC, KMS, CloudTrail).",

    # PR.DS — Data Security
    "PR.DS-01": "Provide: (1) AWS Config rule compliance reports for encryption controls (S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED, ENCRYPTED_VOLUMES, RDS_STORAGE_ENCRYPTED), (2) KMS key policy documentation showing key management approach, (3) Security Hub findings for encryption-related controls.",
    "PR.DS-02": "Provide: (1) ACM certificate inventory showing TLS certificates in use, (2) ALB/CloudFront listener configurations showing HTTPS-only policies, (3) S3 bucket policies requiring aws:SecureTransport, (4) VPC endpoint configurations for private AWS service access.",
    "PR.DS-10": "Provide: (1) Documentation of data-in-use protection measures, (2) AWS Nitro Enclave configurations if used for sensitive processing, (3) Application-level encryption or tokenization documentation for sensitive data in memory.",
    "PR.DS-11": "Provide: (1) AWS Backup policy configurations showing retention periods and cross-Region replication, (2) Backup restoration test records with dates and results, (3) Backup Vault Lock configuration evidence, (4) KMS key configuration for backup encryption.",

    # PR.PS — Platform Security
    "PR.PS-01": "Provide: (1) AWS Config conformance pack or Security Hub standard compliance reports (CIS AWS Foundations, AWS FSBP), (2) Configuration baseline documentation, (3) Auto-remediation rule configurations for common misconfigurations, (4) Configuration drift detection reports.",
    "PR.PS-02": "Provide: (1) Systems Manager Patch Manager compliance reports showing patch status, (2) Amazon Inspector vulnerability findings for EC2 and containers, (3) ECR image scan results, (4) End-of-life tracking records for operating systems and runtimes.",
    "PR.PS-03": "Provide: (1) Hardware maintenance schedules and records for on-premises equipment, (2) AWS Artifact SOC reports for AWS-managed hardware, (3) End-of-life replacement plans for network equipment connected to AWS.",
    "PR.PS-04": "Provide: (1) CloudTrail configuration showing multi-region, management and data event logging enabled, (2) CloudWatch Log group retention policy configurations, (3) Centralized logging architecture documentation (logging account S3 bucket with Object Lock), (4) VPC Flow Log and S3 access log configurations.",
    "PR.PS-05": "Provide: (1) EC2 Image Builder hardened AMI configurations, (2) AWS Organizations SCPs restricting unauthorized services or regions, (3) Systems Manager application control configurations or allowlists.",
    "PR.PS-06": "Provide: (1) CI/CD pipeline configuration showing security scanning stages (SAST, DAST, dependency scanning), (2) CodeGuru or third-party code review tool reports, (3) Dependency vulnerability scan results from build pipeline, (4) Secure SDLC policy documentation.",

    # PR.IR — Technology Infrastructure Resilience
    "PR.IR-01": "Provide: (1) Security group configurations with least-privilege rules, (2) Network ACL configurations, (3) AWS Network Firewall or WAF rule sets, (4) VPC architecture diagrams showing network segmentation (separate VPCs/accounts for dev/staging/prod).",
    "PR.IR-02": "Provide: (1) Multi-AZ deployment configurations for critical workloads, (2) Multi-Region architecture documentation if applicable, (3) AWS Artifact SOC reports documenting AWS data center environmental protections.",
    "PR.IR-03": "Provide: (1) Auto Scaling group configurations, (2) Multi-AZ RDS deployment evidence, (3) S3 cross-Region replication configurations, (4) Route 53 health check and failover routing configurations, (5) Disaster recovery test records or chaos engineering exercise results (AWS Fault Injection Service).",
    "PR.IR-04": "Provide: (1) Auto Scaling policies and configurations, (2) CloudWatch capacity alarms, (3) Trusted Advisor service limit check results, (4) Reserved capacity or savings plan documentation for critical workloads.",

    # DE.CM — Continuous Monitoring
    "DE.CM-01": "Provide: (1) VPC Flow Log configurations and sample analysis reports, (2) GuardDuty network-based finding examples and response records, (3) AWS Network Firewall alert log configurations, (4) SIEM integration evidence showing network event ingestion.",
    "DE.CM-02": "Provide: (1) AWS Artifact SOC reports documenting AWS data center physical monitoring, (2) For on-premises infrastructure — environmental monitoring system reports (temperature, humidity, power, water detection).",
    "DE.CM-03": "Provide: (1) CloudTrail API activity monitoring configuration, (2) GuardDuty anomalous behavior detection findings and response records, (3) IAM Access Analyzer access pattern reports, (4) Evidence of insider threat monitoring procedures.",
    "DE.CM-06": "Provide: (1) Third-party access IAM role configurations with scoped permissions and external ID conditions, (2) CloudTrail logs showing third-party API activity monitoring, (3) Vendor access review records.",
    "DE.CM-09": "Provide: (1) Amazon Inspector continuous scanning configuration and findings reports, (2) GuardDuty runtime monitoring configuration (EC2, ECS, EKS, Lambda protection status), (3) CloudWatch application-level monitoring dashboards and anomaly detection configurations.",

    # DE.AE — Adverse Event Analysis
    "DE.AE-02": "Provide: (1) Amazon Detective investigation examples showing entity relationship visualization, (2) CloudTrail Lake query examples used for security analysis, (3) SIEM correlation rule documentation and sample alert investigations.",
    "DE.AE-03": "Provide: (1) Security Hub configuration showing all integrated finding sources (GuardDuty, Inspector, Macie, Config, third-party), (2) Cross-source correlation examples, (3) SIEM or Security Hub aggregation dashboard screenshots.",
    "DE.AE-04": "Provide: (1) Incident severity classification criteria documentation, (2) Amazon Detective scope analysis examples, (3) Sample impact assessments from recent security events showing how scope was determined.",
    "DE.AE-06": "Provide: (1) Security Hub notification configurations (SNS, EventBridge, PagerDuty, Slack integrations), (2) Tiered notification routing rules based on severity, (3) Evidence of notification delivery for recent security events.",
    "DE.AE-07": "Provide: (1) GuardDuty custom threat list configurations, (2) Threat intelligence enrichment procedures for Security Hub findings, (3) Examples of threat intel integration influencing triage decisions.",
    "DE.AE-08": "Provide: (1) Documented incident declaration criteria mapping to finding severity levels, (2) Incident declaration authority documentation, (3) Records of recent incident declarations showing criteria were applied.",

    # RS.MA — Incident Management
    "RS.MA-01": "Provide: (1) Incident response plan document with AWS-specific runbooks (compromised credentials, S3 data exposure, unauthorized EC2), (2) Third-party coordination procedures (AWS Support, law enforcement, regulators), (3) AWS Enterprise Support or IDR engagement records if applicable.",
    "RS.MA-02": "Provide: (1) Incident triage workflow documentation, (2) Security Hub workflow status records or incident management platform (PagerDuty, ServiceNow) ticket examples showing triage process.",
    "RS.MA-03": "Provide: (1) Incident severity classification system documentation (e.g., SEV1-SEV4), (2) Mapping between GuardDuty severity levels and internal severity classifications, (3) Examples of categorized incidents.",
    "RS.MA-04": "Provide: (1) Escalation procedure documentation with criteria for each escalation level, (2) Escalation contact lists (management, legal, communications, AWS Support), (3) Records of recent escalations.",
    "RS.MA-05": "Provide: (1) Recovery initiation criteria documentation, (2) Examples of recovery decisions showing criteria were applied after containment was confirmed.",

    # RS.AN — Incident Analysis
    "RS.AN-03": "Provide: (1) Root cause analysis reports from recent incidents, (2) Amazon Detective investigation screenshots or exports, (3) CloudTrail Lake query results used for forensic timeline reconstruction, (4) Forensic analysis procedures for EC2 instances (EBS snapshot analysis, memory capture).",
    "RS.AN-06": "Provide: (1) CloudTrail log storage configuration showing immutability (S3 Object Lock), (2) Chain of custody procedures for forensic evidence, (3) Investigation action logs from recent incidents.",
    "RS.AN-07": "Provide: (1) Evidence collection procedures documentation, (2) Automated evidence collection scripts or runbooks (EBS snapshots, metadata capture, CloudTrail export), (3) Evidence storage location with access controls.",
    "RS.AN-08": "Provide: (1) Incident magnitude estimation procedures, (2) Amazon Detective scope analysis or Macie data exposure assessment examples, (3) Sample magnitude reports from recent incidents.",

    # RS.CO — Incident Response Reporting and Communication
    "RS.CO-02": "Provide: (1) Incident notification templates for different stakeholder types, (2) Notification contact lists and escalation procedures, (3) Regulatory notification timeline documentation (PCI, HIPAA, GDPR requirements), (4) Records of notifications sent for recent incidents.",
    "RS.CO-03": "Provide: (1) Information sharing procedures and approval workflows, (2) War room or incident management platform configuration, (3) Status update templates and distribution records.",

    # RS.MI — Incident Mitigation
    "RS.MI-01": "Provide: (1) Containment runbooks for common AWS scenarios (security group isolation, IAM credential revocation, WAF IP blocking, access key disabling), (2) Automated containment Lambda functions or Security Hub custom action configurations, (3) Containment action records from recent incidents with timestamps.",
    "RS.MI-02": "Provide: (1) Eradication procedures documentation (unauthorized resource removal, credential rotation, vulnerability patching, system rebuild from known-good images), (2) Eradication action records from recent incidents.",

    # RC.RP — Incident Recovery Plan Execution
    "RC.RP-01": "Provide: (1) Recovery plan document with AWS-specific procedures (AWS Backup restoration, CloudFormation/CDK redeployment, DR region failover), (2) Recovery initiation authorization records, (3) Recovery exercise or drill records.",
    "RC.RP-02": "Provide: (1) Critical system priority list with RTOs and RPOs, (2) Recovery sequencing documentation, (3) Records of recovery action prioritization from recent incidents or exercises.",
    "RC.RP-03": "Provide: (1) Backup integrity verification procedures, (2) AWS Backup recovery point validation records, (3) Evidence of clean EBS snapshot and trusted AMI verification before restoration.",
    "RC.RP-04": "Provide: (1) Post-incident security review procedures, (2) Updated baseline documentation after recovery, (3) Additional monitoring or controls implemented before returning to normal operations.",
    "RC.RP-05": "Provide: (1) Restored asset integrity verification procedures (Inspector scans, Config compliance checks on restored systems), (2) Service health confirmation records, (3) Production readiness sign-off documentation.",
    "RC.RP-06": "Provide: (1) Incident closure criteria documentation, (2) Post-incident review (lessons learned) reports, (3) Incident response plan update records based on lessons learned, (4) Final incident documentation package.",

    # RC.CO — Incident Recovery Communication
    "RC.CO-03": "Provide: (1) Recovery status update records sent to stakeholders, (2) Final recovery report documenting restoration of operational capabilities.",
    "RC.CO-04": "Provide: (1) Public communication templates and approval procedures, (2) Designated spokesperson documentation, (3) Records of public statements coordinated with legal and communications teams.",
}


def get_csf_evidence_question(subcategory_id: str) -> Optional[str]:
    """Get custom evidence question for a CSF subcategory.

    Args:
        subcategory_id: CSF subcategory ID (e.g., 'GV.OC-01')

    Returns:
        Evidence question string if exists, None otherwise
    """
    return CSF_EVIDENCE_QUESTIONS.get(subcategory_id.upper())


def has_csf_evidence_question(subcategory_id: str) -> bool:
    """Check if a custom evidence question exists for a CSF subcategory."""
    return subcategory_id.upper() in CSF_EVIDENCE_QUESTIONS


def get_csf_custom_questions(subcategory_id: str) -> Optional[List[Dict[str, str]]]:
    """Get custom implementation questions for a CSF subcategory.

    Args:
        subcategory_id: CSF subcategory ID (e.g., 'GV.OC-01', 'PR.DS-01')

    Returns:
        List of question dicts if custom questions exist, None otherwise
    """
    return CSF_CUSTOM_QUESTIONS.get(subcategory_id.upper())


def has_csf_custom_questions(subcategory_id: str) -> bool:
    """Check if custom implementation questions exist for a CSF subcategory.

    Args:
        subcategory_id: CSF subcategory ID

    Returns:
        True if custom questions exist
    """
    return subcategory_id.upper() in CSF_CUSTOM_QUESTIONS
